### ISSUE TITLE
Conditional next step

### ISSUE THREAD

**Issue by nadeemja** [LucasBassetti/react-simple-chatbot#1]
Hi,

This looks very good! 

From what I can see, there is no support for conditional next step. 

Will this be added in the future? 

Thanks :)

**Comment by LucasBassetti** [comment]
Hi @nadeemja,

I'm glad that you like it!

What do you means with conditional step? 

There is the options step that you can define conditions and trigger different steps according with user answer (check [this example](http://lucasbassetti.com.br/react-simple-chatbot/#/docs/options))

Thanks!
