### ISSUE TITLE
close windows with X?

### ISSUE THREAD

**Issue by sushantshek20** [LucasBassetti/react-simple-chatbot#101]
I am using the bot with these props : 
 floating={true}
 opened={true}

I know its possible to use toggleFloating to toggle the chatbot open and close. but I want to use that X button on the top right to close the tab in which the bot is opened rather than to toggle close the chatbot. how can I achieve this?

**Comment by LucasBassetti** [comment]
Hi @sushantshek20,

You should use the `toggleFloating` prop to change the `opened` prop. Check the documentation [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot)
