### ISSUE TITLE
"npm install" not working, how else can i contribute?

### ISSUE THREAD

**Issue by gukii** [LucasBassetti/react-simple-chatbot#102]
## Description

As described in past (closed) issues (e.g. https://github.com/LucasBassetti/react-simple-chatbot/issues/3) , "git clone" followed by "npm install" is throwing errors.

I wonder how the protocol looks like for people to contribute to this repo.

`npm install react-simple-chatbot --save 
installs the distribution which is not very readable and challenge to edit ;-)

**Comment by wrrnwng** [comment]
I got this working by moving all the `peerDependencies` in `package.json` to `dependencies`, but obviously this isn't very intuitive to anyone trying contribute to this project running it for the first time.

**Comment by gukii** [comment]
That totally worked. Thx wrrnwng!
