### ISSUE TITLE
The enter button gets hidden during user input in iphone

### ISSUE THREAD

**Issue by vysakh0** [LucasBassetti/react-simple-chatbot#103]
In iPhone (11.4), the enter button gets hidden during user input. One has to scroll to the left side to see the enter button on the right side. 
I think during user input in the chat there's a zoom in (in iPhone) which hides the submit button. 
It'd be nice to have a fix, it works great in other devices and browsers. Love this library 💛💚

**Comment by PrakashMurugan** [comment]
![img-20180601-wa0003](https://user-images.githubusercontent.com/38039415/40908476-76cdecb4-6804-11e8-9939-0d80a644432a.png)

I have the same issue in iphone 😢 (in iPhone x, iPhone 7 with 11.4 iOS). Not only the submit button, the entire user side chat on the left side gets hidden.

**Comment by LucasBassetti** [comment]
Did you try zoom out? Also, are using the version `0.3.0`?

**Comment by PrakashMurugan** [comment]
It works with the latest `0.3.0` version! Thank you!!

**Comment by vysakh0** [comment]
👍 it works! thanks
