### ISSUE TITLE
Caching chatbot with custom components exceeds the 5MB quota 

### ISSUE THREAD

**Issue by vidimitrov** [LucasBassetti/react-simple-chatbot#104]
## Description

Hello and congrats for the amazing project :)

I'm using it to create an app with conversational interface, not a traditional bot which usually is either opened or closed. Based on the conversation that goes with the bot it either redirect internally, externally or do something custom. For 90% of my needs the projects is more than amazing and already saved me a lot of time!
Unfortunately I encountered an issue that I'm still thinking how to solve and wanted to know if you already have some ideas.

The issue is the following: When I use a custom component in a step like:

`{
    id: 'projects-slider',
    component: (<ProjectsSlider projects={projects} />),
  }`

everything works as expected but if I pass `cache={true}` to the ChatBot component, which is my desired behavior there is a problem when it attempt to store it in localStorage - it exceeds the quota of 5MB... 

I already stringified the `data` object manually and it really become 5.4MB only because of the  `<ProjectsSlider />` component and all the React related props that comes with it. Without it normal steps cache is around  10-15KB.

My initial thought was that there is something extremely wrong with my component... But I refactored everything I could, and still get the same size. Here is how the  component looks like:

[ProjectsSlider.jsx](https://gist.github.com/vidimitrov/77b890f22b404ed730b98bea0a08eb72)

To reproduce the issue, just add any component which is a little bit more advanced than `<div>Some custom test component</div>`. Testing environment is Google Chrome on MacOS. 

There are two solutions that come to my mind at the moment... either change the storage module to be able to change the storage provider and use IndexedDB or something else or change the way the module is caching custom components. My gut feeling is that  the second approach would be more elegant, but both of them would take me some time to implement.

Thats why I wanted to know if you encountered the same issue, if it is only for me, or if it is a known issue are there any plans for solving it. 
Tell me what you think, regarding solving the issue. I would be more than happy to contribute once we come up with a solution that fits the needs of both sides :)

Thanks again!  The project is great :)

## Screenshots
<img width="658" alt="screen shot 2018-05-31 at 10 53 42 pm" src="https://user-images.githubusercontent.com/3698434/40806211-7cb81678-6529-11e8-8495-1826ec8d5bf3.png">

**Comment by LucasBassetti** [comment]
Hi @vidimitrov,

Can you update to `0.3.0` and tell me if works?

**Comment by vidimitrov** [comment]
Hi @LucasBassetti 

It works! 
Tested it with several components and I confirm that I couldn't reproduce the issue anymore.

Thanks a lot for the immediate help and your amazing project!
