### ISSUE TITLE
Jump messages with Validation?

### ISSUE THREAD

**Issue by sushantshek20** [LucasBassetti/react-simple-chatbot#110]
Is it possible to jump to different message IDs with validation?

Use Case : 
I am asking for the Email Address, if the email address is invalid I wish to send another message saying please enter your correct message instead of showing the validation error.

**Comment by LucasBassetti** [comment]
Hi,

You can do that. Please check this [example](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/validator)

**Comment by Saibabu520** [comment]
Please give an example

**Comment by bottleneckdvlpr** [comment]
Write your own. Don't be a baby.
