### ISSUE TITLE
No option to change the minimized svg icon while in  floating  mode

### ISSUE THREAD

**Issue by vinayprajapatiaurotfp** [LucasBassetti/react-simple-chatbot#112]
## Description
No option to change the minimized svg icon while in  floating  mode

I tried to find out if there is an option available to change the icon when in floating mode. There are options to change botAvatar, userAvatar but no option to change the minimized icon

## Screenshots
![image](https://user-images.githubusercontent.com/34682499/42261997-83e6532e-7f87-11e8-88d9-a43c2709f533.png)

![image](https://user-images.githubusercontent.com/34682499/42262007-8ebc89f8-7f87-11e8-8f18-d65760cd1fe1.png)

## Expectation
We must have an option to change the svg image just like avatars and also styling for same.

**Comment by vinayprajapatiaurotfp** [comment]
@LucasBassetti Would be great if you could incorporate this feature, or let me know in case you don't have time for it and I could try my hands there and raise a PR.

**Comment by vinayprajapatiaurotfp** [comment]
@LucasBassetti  Can we please keep it opened?

**Comment by vinayprajapatiaurotfp** [comment]
@LucasBassetti  I downloaded this project but it doesn't have the source code. Can you please share if there are any steps to access source code and raise PR?

**Comment by vinayprajapatiaurotfp** [comment]
@LucasBassetti  I have changes ready with me but I can't push the changes. Can you please allow me to submit code to a new branch?

**Comment by LucasBassetti** [comment]
You need fork the project and create a Pull Request

**Comment by ejuarez1293** [comment]
@vinayprajapatiaurotfp Was this ever posted?

**Comment by vinayprajapatiaurotfp** [comment]
@ejuarez1293  nope. I had done the work but didn't get time to raise a PR.

**Comment by LucasBassetti** [comment]
Hi. Please use the latest version and the [floatingIcon](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot) prop
