### ISSUE TITLE
toggleFloating

### ISSUE THREAD

**Issue by wireless90** [LucasBassetti/react-simple-chatbot#113]
## Description
Hi could you give a **code example** of how to use toggle floating.

I have set floating to true.
I have set opened to true.

Chatbot's initial state is opened as expected.

But I also want it to minimize when I click the close button.

**Comment by vinayprajapatiaurotfp** [comment]
you have to add call to `toggleFloating`

**Comment by wireless90** [comment]
Sorry guys could you give an example, would help a lot.

**Comment by LucasBassetti** [comment]
```
import React, { Component } from 'react';
import ChatBot from 'react-simple-chatbot';

class Example extends Component {
  state = {
    opened: false
  }

  toggleFloating = ({ opened }) => {
    this.setState({ opened }); 
  }

  render() {
    const { opened } = this.state;
    const steps = [
      {
        id: 'hello-world',
        message: 'Hello World!',
        end: true,
      },
    ];

    return (
      <ChatBot
        steps={steps}
        floating={true}
        opened={opened}
        toggleFloating={this.toggleFloating}
      />
    )
  }
}
```

**Comment by lakshya-webDev** [comment]
how to add close button to chat bot @LucasBassetti 
![Screenshot (16)](https://user-images.githubusercontent.com/67680728/124897881-56720e00-dffc-11eb-9170-25e799dd281e.png)

can you please help me out
