### ISSUE TITLE
Invalid key 'avatar' in step where I change component to a message. 

### ISSUE THREAD

**Issue by chaodonghu** [LucasBassetti/react-simple-chatbot#12]
The avatar reverts to the user avatar when I change a component to a message.

**Comment by chaodonghu** [comment]
![screen shot 2017-07-18 at 3 19 19 pm](https://user-images.githubusercontent.com/22258898/28335274-d08c1b1c-6bcb-11e7-86b3-e69be46ba2a2.png)

**Comment by LucasBassetti** [comment]
Hi, Thanks for reporting.

I will try to solve that ASAP.

**Comment by LucasBassetti** [comment]
Fixed in `v0.2.1`

**Comment by chaodonghu** [comment]
Thank you!
