### ISSUE TITLE
[Question] Modifying the look and placement of FloatButton

### ISSUE THREAD

**Issue by smasschelin** [LucasBassetti/react-simple-chatbot#120]
Hello,

Is/are there parameters that control the look of the float button?  For example, I'd like to have the icon be a square/an image and have it placed at the bottom center of a page. Ideally I'd like to modify much like how the bot avatar or style is modified via a parameter that is passed to the chatbot class.

Thank you

**Comment by Luismi74** [comment]
same here Lucas, I did send the BeerPay $ pls help

**Comment by LucasBassetti** [comment]
Custom floating add in the version `0.3.6`. 

Now you can use the `floatingStyle` prop to customize the floating. Example:

```
<ChatBot
      steps={steps}
      floating={true}
      floatingStyle={{
        left: 'calc(50% - 28px)',
        right: 'initial',
        transformOrigin: 'bottom center',
        borderRadius: 0,
      }}
      style={{
        left: 'calc(50% - 175px)',
      }}
/>
```

**Comment by smasschelin** [comment]
Thank you so much! Really appreciate it. Your module is amazing.

**Comment by Luismi74** [comment]
Does this work with the React Native too?
