### ISSUE TITLE
Can you give an example for string validator? And for jumping messages

### ISSUE THREAD

**Issue by Saibabu520** [LucasBassetti/react-simple-chatbot#121]
Please give an example for string validator. I found number validator in documentation but I need string validator. Based on validation I will trigger.
Usecase: Suppose I'm checking user input for specific word like 'facebook' then I will trigger to Facebook info. If I get word from user input like 'twitter' I will trigger to Twitter info.

Thanks in advance.

**Comment by LucasBassetti** [comment]
I think this is not related with validation. You can use the [Option step](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps) for that or create a [custom component](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component) that will receive a value from the user and return some info based on this value. Like [this example](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)
