### ISSUE TITLE
How to pass user selected option to component? Please give an example.

### ISSUE THREAD

**Issue by Saibabu520** [LucasBassetti/react-simple-chatbot#122]
I want to pass user selected option or input to a component. How can we do that? Please give one example...

Thanks in advance...

**Comment by LucasBassetti** [comment]
Hi @Saibabu520,

Please take a look in this [example](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)

Basically I'm getting the user input and making a search on DBPedia.
