### ISSUE TITLE
Change Chat Icon 

### ISSUE THREAD

**Issue by christianortega123** [LucasBassetti/react-simple-chatbot#127]
Hi, I am wanting to change the the chat icon below to something else:

<img width="100" alt="screen shot 2018-08-07 at 3 52 48 pm" src="https://user-images.githubusercontent.com/22563806/43806751-23b721ca-9a5a-11e8-9f01-ea60a3a0cc79.png">

I tried to do this by changing the svg located in the following directory:
`/react-simple-chatbot-master/lib/icons/ChatIcon.jsx`

The code located here is as follows (posted a screenshot bc formatting wasn't working for some reason):

![screen shot 2018-08-07 at 4 00 24 pm](https://user-images.githubusercontent.com/22563806/43806964-25cf7d58-9a5b-11e8-8d81-a0f6bbf5eaec.png)

I have my svg ready and have tried replacing the one in the code above but no matter what I do,
even if I delete the code that's already there, the chat icon remains in place and does not change.

Is there a way to change it?

Thank you!

**Comment by LucasBassetti** [comment]
Hi,

Unfortunately not yet. But I will consider this for the next release. PRs are welcome 👍

**Comment by PraveenK311** [comment]
Hi, I am wanting to change the the chat icon below to something else:

I tried to do this by changing the SVG located in my directory but could not able to change, is there any way to change the SVG icon as customized one
