### ISSUE TITLE
Chatbot taking default value instead of updated value....

### ISSUE THREAD

**Issue by Saibabu520** [LucasBassetti/react-simple-chatbot#128]
Hi,

--> Actually i created one state object with 1 value with default value like below---
  ```
constructor(props){
    super(props);
    this.state = {
      planSelected: 'planName'
    };
}

```
--> Im getting one value from child component and updating the above object value with the latest value what i got from child...
--> Im successfully fetching value from child component and i override the previous value..

```
fetchData = (choosenPlan) => {
   this.setState({
   planSelected: choosenPlan
 });
```

--> After assigning new value , Im passing this new updated value of  "planSelected" variable to some other child component using custom component like below....
```
{
          id: 'selectedPlanDeals',
          component: `<FetchPlanDeals planState = {this.state.planSelected}/>`,
           asMessage: true,
           trigger: 'userQuery',
 },

```
--> Problem is i'm not getting the updated value of "planSelected" in FetchPlanDeals component it is taking whatever default value i assigned. It is not taking overridden value........

--> Please give any solution. This is blocking my work.

Thanks in advance.

**Comment by LucasBassetti** [comment]
Why you not put the `planSelected` state in the `FetchPlanDeals` component?

**Comment by Saibabu520** [comment]
Sorry I didn't get plz give example

**Comment by Saibabu520** [comment]
I think when chatbot rendering, what and all values we are accessing inside chatbot those initial values only it was taking not updated values.

**Comment by Saibabu520** [comment]
After return() also im getting updated value only inside `<ChatBot>` im not getting updated value.
Everywhere im getting updated value except in `<ChatBot>` tag.
```
render() {
    return (
      <div className="docs-example-1">
      <h1>{this.state.planSelected}</h1>
        <ChatBot
          handleEnd={this.handleEnd}
          floating='true'
          headerTitle='ChatBot'
          steps={} />
      );
  )
```

Please check it once why it is happening like this . It is blocking my work.

**Comment by Saibabu520** [comment]
Hi, i given sample code for problem which im facing in my code.

`
import React from 'react';
import ChatBot from 'react-simple-chatbot';

class Testing extends React.Component {

  constructor(){
    super();
    this.state = {
      language: 'hindi'
    };
  }
  choosenLanguage  = (value) => {
    this.setState({
    language: value
  });
  }

  render() {
    return (
      <div>
      <h1>Before ChatBot {this.state.language}</h1>
        <ChatBot
          floating='true'
          inputAttributes={this.state.language}
          steps={[
              {
                id: 'name',
                message: 'Please select language',
                trigger: 'select',
              },
              {
                id: 'select',
                component: <ChildComponent sl={this.choosenLanguage}/>,
                waitAction: true,
                trigger: () => {
                         if (this.state.language != undefined) {
                           return 'final';
                         }
                }
              },
              {
                id: 'final',
                message: this.state.language,
                end:true,
              }
          ]}
        />
      </div>
    );
  }
}

class ChildComponent extends React.Component {

  constructor(props){
    super(props);
    this.state = {
      selectedLang:''
    }
  }
  setLang() {
    this.props.sl(this.state.selectedLang);
  }
  render() {
           return (
             <div>
                 <button onClick={() => {
                   this.state.selectedLang = 'Hindi',
                   this.setLang()
                 }}> Hindi
                 </button>
                 <button onClick={() => {
                   this.state.selectedLang = 'English',
                   this.setLang()
                 }}> English
                 </button>
            </div>
              );
 }
}
export default Testing;
`
Please solve this code.

**Comment by LucasBassetti** [comment]
You can just pass attributes between steps. So if you select the language in the `name` step you need look for the `steps.name` in the custom component. Check the [props received by Custom Component](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component)

**Comment by chandjenAC** [comment]
> Why you not put the `planSelected` state in the `FetchPlanDeals` component?

That is what he did
