### ISSUE TITLE
How to change chatbot icon?

### ISSUE THREAD

**Issue by Saibabu520** [LucasBassetti/react-simple-chatbot#129]
Hi,

I want to change the icon of chatbot. Is there any chance to put jpeg or png image instead of svg for chatbot?.

Thanks in advance

**Comment by LucasBassetti** [comment]
Hi,

Unfortunately not yet. But I will consider this for the next release. PRs are welcome 👍

**Comment by ShivaniKshatriya** [comment]
Hello, Do we have any update on changing chatbot icon
