### ISSUE TITLE
Add a submit/send button to the user input area

### ISSUE THREAD

**Issue by bobissict** [LucasBassetti/react-simple-chatbot#13]
Hi Lucas,

First of all thanks so much for an amazing piece of open source 👏

One thing that I think could be really helpful is to add a submit/send button to the user input area, like the below screenshot.

<img width="375" alt="screen shot 2017-07-20 at 2 58 36 pm" src="https://user-images.githubusercontent.com/12051210/28418463-11c72374-6d5c-11e7-871d-d6d175b8e041.png">

Main reason being is that if you're using the chatbot on a mobile device and you enter something into the input and hit the `done` button then it doesn't submit. You need to hit the `return` button to get it to submit. See screenshot below

![image uploaded from ios 2](https://user-images.githubusercontent.com/12051210/28418692-ea5810e0-6d5c-11e7-95e4-5c2e39f0602c.jpg)

So I think there may be 2 solutions:
1. Add a submit button like suggested above
2. `Done` button on the keyboard also submits the form (not sure if possible)

Thanks again, look forward to hearing back from you.

Regards
Bo

**Comment by LucasBassetti** [comment]
Hi @bobissict,

I will try to find a solution for this ASAP.

Thanks for reporting!

Best regards,
Lucas

**Comment by LucasBassetti** [comment]
submit button added in `v0.2.2`

**Comment by bobissict** [comment]
legend, thank you 🙌🏻
