### ISSUE TITLE
how to display user message from custom component?

### ISSUE THREAD

**Issue by savanchhayani** [LucasBassetti/react-simple-chatbot#131]
I want to create chat bot UI and want to hide text input throughout the whole process and handle using the custom component.

One way is that i use the previousValue to display the user message. 
I want to do is:
- Hide text input,
- Display message as a user from the custom component.

**Comment by LucasBassetti** [comment]
Hi,

for hide text input you can use the [hideInput](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps) in the steps (but you can't use in the user step)

I didn't understand the second one. Custom component can just be used in the bot side. User side is just for show user messages. But you can create a custom component with an input for users type.

**Comment by BharathKhan5** [comment]
hi,

how can we add image component in chatbot...

**Comment by savanchhayani** [comment]
Hi, @LucasBassetti Thank you for the answer :)
My second question is how can I create a custom component with an input for users type.
Thank you again :)

**Comment by LucasBassetti** [comment]
Check an example of Custom Component [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)

**Comment by sjain3097** [comment]
Like if i create a custom component and have some options diplaying inside it.
When the user selects one option, I want to display that option from user side
is it possible?

**Comment by GMoHughes** [comment]
Hi - has this been built in?

Will fork if not.

Essentially if I have a custom component with options/location search/etc , id like the response to show as a user message upon response given in custom component

**Comment by fortydegrees** [comment]
@GMoHughes any luck or update with that? I've got the same problem. I display a <Picker> RN component, and want to display it as a user's message after they select.

**Comment by fortydegrees** [comment]
I manage to create a little custom hack to accomplish this. Fork/clone the repo into your directory (for what it's worth, I used react-native-chatbot-expo, but I'm guessing it's the same).

in /ChatBot.js, add this to the renderStep function, just after all the const declarations at the beginning:

`if(step.metadata && step.metadata.custom) step.user = true`

Then, you can simply pass 'custom: true' in the metadata field like so:

```
    {
      id: '0',
      message: 'Hi! 👋',
      trigger: 'next',
      metadata: {custom: true}
    },
```

I realise now that the colour, avatar etc. are the same as the bot, but if you've got that far it should be easy to just amend the styles.

**Comment by diegobonfim182** [comment]
> I manage to create a little custom hack to accomplish this. Fork/clone the repo into your directory (for what it's worth, I used react-native-chatbot-expo, but I'm guessing it's the same).
> 
> in /ChatBot.js, add this to the renderStep function, just after all the const declarations at the beginning:
> 
> `if(step.metadata && step.metadata.custom) step.user = true`
> 
> Then, you can simply pass 'custom: true' in the metadata field like so:
> 
> ```
>     {
>       id: '0',
>       message: 'Hi! 👋',
>       trigger: 'next',
>       metadata: {custom: true}
>     },
> ```
> 


Hi @fortydegrees I did not understand where specifically inside the file /react-simple-chatbot.js, I could insert this code: if(step.metadata && step.metadata.custom) step.user = true . 

Can you please explain with details where exactly. If it´s inside some function for exemple. I am using ReactJs version. Can you paste a print of your file?

**Comment by diegobonfim182** [comment]
@LucasBassetti

**Comment by diegobonfim182** [comment]
Like if i create a custom component and have some options diplaying inside it.
When the user selects one option, I want to display that option from user side
is it possible?

**Comment by vishalgupta888** [comment]
> 
@diegobonfim182 did you find any way to do it?
