### ISSUE TITLE
Chatbot fullscreen height doesn't working.

### ISSUE THREAD

**Issue by savanchhayani** [LucasBassetti/react-simple-chatbot#132]
Hi,

I've modify the height and width of the ChatBot.

I used the style for fullscreen is:
<ChatBot
style= {{height: '100vh', width: '100%'}}
steps={steps}
/>

Setting a fullscreen height, text input is displaying in the middle of the chatbot and not to the bottom of the bot.

![screen shot 2018-08-20 at 12 50 21 pm](https://user-images.githubusercontent.com/32090577/44380317-374f0300-a528-11e8-9e30-24f937bd306c.png)

**Comment by LucasBassetti** [comment]
Hi, try use the [contentStyle](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot) prop.
