### ISSUE TITLE
how its working with React 15.6.2 version

### ISSUE THREAD

**Issue by monikapathania** [LucasBassetti/react-simple-chatbot#135]
I installed https://www.npmjs.com/package/react-simple-chatbot/v/0.3.7
with my React 15.6.2 verison but its not working 
there is any solution for it 
Please suggest something.

**Comment by LucasBassetti** [comment]
Update your React package to version 16

**Comment by monikapathania** [comment]
sorry, we can't update it 
there is any other suggest?

**Comment by LucasBassetti** [comment]
Try to use the `v0.2.7`
