### ISSUE TITLE
different coloured quick reply?

### ISSUE THREAD

**Issue by sushantshek20** [LucasBassetti/react-simple-chatbot#137]
How to set different color to quick reply than the color that is set for Bot messages?

**Comment by cubissimo** [comment]
it's super usefull to have 👍

**Comment by cubissimo** [comment]
@sushantshek20 i just overwrite bellow style to got what i need:

```
 .rsc-os-option-element{
    background-color:#4D5AFF;
    color:#fff;
  }
```

**Comment by aaronkrohn** [comment]
@sushantshek20 The chat uses styled-components in mind so you can pass `ThemeProvider` a theme object to override the colours to want:

`  
import { ThemeProvider } from 'styled-components';

const theme =  {
        background: '#f5f8fb',
        fontFamily: 'Helvetica Neue',
        headerBgColor: '#EF6C00',
        headerFontColor: '#fff',
        headerFontSize: '15px',
        botBubbleColor: '#EF6C00',
        botFontColor: '#fff',
        userBubbleColor: '#fff',
        userFontColor: '#4a4a4a',
    }

<ThemeProvider theme={theme}>
    <ChatBot />
</ThemeProvider>
`
Hope this helps

**Comment by cubissimo** [comment]
Ca we override the option style with ThemeProvider? Cause in docs says only this properties can be overrided:

`background: '#f5f8fb',
        fontFamily: 'Helvetica Neue',
        headerBgColor: '#EF6C00',
        headerFontColor: '#fff',
        headerFontSize: '15px',
        botBubbleColor: '#EF6C00',
        botFontColor: '#fff',
        userBubbleColor: '#fff',
        userFontColor: '#4a4a4a',`

nothing mentioning Options bubble

**Comment by aaronkrohn** [comment]
@cubissimo Yes very true. In any case you can change the option bubble with the `bubbleOptionStyle` prop

**Comment by GilbertMizrahi** [comment]
@aaronkrohn can you say more.  For example, if you want to change font-size, color, and background-color, how would you do that  with the bubbleOptionStyle prop?

**Comment by sushantshek20** [comment]
@cubissimo  where exactly do I need to   overwrite the style?
