### ISSUE TITLE
Wikipédia Search 

### ISSUE THREAD

**Issue by BharathKhan5** [LucasBassetti/react-simple-chatbot#138]
is not working.. 

error :  Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.
    at invariant (invariant.js:42)
    at instantiateReactComponent (instantiateReactComponent.js:72)
    at Object.updateChildren (ReactChildReconciler.js:115)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:204)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:308)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:295)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:944)
    at ReactDOMComponent.updateComponent (ReactDOMComponent.js:758)
    at ReactDOMComponent.receiveComponent (ReactDOMComponent.js:720)
    at Object.receiveComponent (ReactReconciler.js:122).

and 

https://dbpedia.org/sparql/?default-graph-uri=https://dbpedia.org&query=%0A%20%20%20%20%20%20select%20*%20where%20%7B%0A%20%20%20%20%20%20?x%20rdfs:label%20%22Brazil%22@en%20.%0A%20%20%20%20%20%20?x%20rdfs:comment%20?comment%20.%0A%20%20%20%20%20%20FILTER%20(lang(?comment)%20=%20%27en%27)%0A%20%20%20%20%20%20%7D%20LIMIT%20100%0A%20%20%20%20&format=json

value

{ "head": { "link": [], "vars": ["x", "comment"] },
  "results": { "distinct": false, "ordered": true, "bindings": [ ] } }

help me plzz

**Comment by LucasBassetti** [comment]
Did you install the chatbot?

**Comment by BharathKhan5** [comment]
Yes.. I installed

**Comment by LucasBassetti** [comment]
I need more information (packages that you installed, piece of code, etc.)

Can you provide that?

**Comment by BharathKhan5** [comment]
Yes. here it is 

import React, { Component } from 'react'; 
import PropTypes from 'prop-types'; 
import Loading from '../lib/steps_components/common/Loading'; 

class DBPedia extends Component { 
constructor(props) { 
super(props); 

this.state = { 
loading: true, 
result: '', 
trigger: false, 
}; 

this.triggetNext = this.triggetNext.bind(this); 
} 

componentWillMount() { 
const self = this; 
const { steps } = this.props; 
const search = steps.search.value; 
console.log('search', search); 
const endpoint = encodeURI('https://dbpedia.org'); 
console.log('endpoint', endpoint); 
const query = encodeURI(` 
select * where { 
?x rdfs:label "${search}"@en . 
?x rdfs:comment ?comment . 
FILTER (lang(?comment) = 'en') 
} LIMIT 100 
`); 
console.log('query', query); 
const queryUrl = `https://dbpedia.org/sparql/?default-graph-uri=${endpoint}&query=${query}&format=json`; 
console.log('queryUrl', queryUrl); 
const xhr = new XMLHttpRequest(); 
console.log('xhr',xhr); 
xhr.addEventListener('readystatechange', readyStateChange); 

function readyStateChange() { 
if (this.readyState === 4 && this.status == 200) { 
console.log('this.responseText', this.responseText); 
const data = JSON.parse(this.responseText); 
console.log('data', data); 
const bindings = data.results.bindings; 
if (bindings && bindings.length > 0) { 
self.setState({ loading: false, result: bindings[0].comment.value }); 
} else { 
self.setState({ loading: false, result: 'Not found.' }); 
} 
} 
} 

xhr.open('GET', queryUrl); 
xhr.send(); 
} 

triggetNext() { 
this.setState({ trigger: true }, () => { 
this.props.triggerNextStep(); 
}); 
} 

render() { 
const { trigger, loading, result } = this.state; 

return ( 
<div className="dbpedia"> 
{loading ? <Loading /> : result} 
{ 
!loading && 
<div 
style={{ 
textAlign: 'center', 
marginTop: 20, 
}} 
> 
{ 
!trigger && 
<button 
onClick={() => this.triggetNext()} 
> 
Search Again 
</button> 
} 
</div> 
} 
</div> 
); 
} 
} 

DBPedia.propTypes = { 
steps: PropTypes.object, 
triggerNextStep: PropTypes.func, 
}; 

DBPedia.defaultProps = { 
steps: undefined, 
triggerNextStep: undefined, 
}; 

export default DBPedia;

**Comment by LucasBassetti** [comment]
Are you getting the code in the source. You need get the code from [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)

**Comment by BharathKhan5** [comment]
yes, 

same code i used but its not work for me.
