### ISSUE TITLE
How can i change my react chat-bot into react-redux chat-bot , its possible ?

### ISSUE THREAD

**Issue by BharathKhan5** [LucasBassetti/react-simple-chatbot#139]
I am going to change my react chat-bot into react-redux chat-bot , its possible

**Comment by LucasBassetti** [comment]
Can you provide more details about what you want to do?

**Comment by BharathKhan5** [comment]
I need to convert react chat bot into redux.

**Comment by LucasBassetti** [comment]
If you want put the steps as a reducer is not possible because the steps need to be pre-defined before start the chatbot.

**Comment by BharathKhan5** [comment]
Hi, 

There is any solution is their to put the steps as a reducer.
