### ISSUE TITLE
Unknown Prop Warning when import chat bot ui

### ISSUE THREAD

**Issue by lichin-lin** [LucasBassetti/react-simple-chatbot#14]
hi! I really like the UI you just made,
but I can't successfully run the ui module.

I got warning like this:
<img width="483" alt="2017-07-29 1 02 35" src="https://user-images.githubusercontent.com/10290616/28728028-a488c214-73f9-11e7-97c9-2286c122f500.png">
is this something relative to: https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by LucasBassetti** [comment]
Hi, thanks for reporting! My Mac is reparing and I can't look it with more details but I imagine you are creating a component step with simple html tag. Try to change it to a react component and it should work.

**Comment by lichin-lin** [comment]
I follow this example: https://lucasbassetti.com.br/react-simple-chatbot/#/docs/hello-world
and paste on the entire code.
I'm not sure if it's my webpack config's problem.

**Comment by LucasBassetti** [comment]
Do you have any link of your cose?

**Comment by lichin-lin** [comment]
```
import { connect } from 'react-redux'
import React, { Component } from 'react'
import ChatBot from 'react-simple-chatbot'
// import Containers from 'containers'
// import Actions from 'js/actions'

class Main extends Component {
    constructor (props) {
        super(props)
        this.state = {
            steps: [
                {
                    id: '1',
                    message: 'What is your name?',
                    trigger: '2'
                },
                {
                    id: '2',
                    user: true,
                    trigger: '3'
                },
                {
                    id: '3',
                    message: 'Hi {previousValue}, nice to meet you!',
                    end: true
                }
            ]
        }
    }
    render () {
        return (
            <ChatBot
                steps={[
                    {
                        id: 'hello-world',
                        message: 'Hello World!',
                        end: true
                    }
                ]}
            />
        )
    }
}

const mapStateToProps = (state, ownProps) => ({
})

const mapDispatchToProps = (dispatch) => ({
})

export default connect(mapStateToProps, mapDispatchToProps)(Main)
```

sorry it has been a while since my last comment :(
I still can't get it work so I did all the style by myself these past two day!

**Comment by LucasBassetti** [comment]
Hi, can you send me your `package.json`?

**Comment by LucasBassetti** [comment]
I can simulate this warning just when I create a simple html component, like that:

```
<ChatBot
        steps={[
          {
              id: '1',
              message: 'Hello',
              trigger: '2'
          },
          {
              id: '2',
              component: <div />,
              end: true,
          },
        ]}
      />
``` 

![image](https://user-images.githubusercontent.com/1014326/28795874-d06629d4-7611-11e7-88db-1d38eea98663.png)

But I can solve this easily change the component to some like that:

``` 
const Example = () => <div />;

<ChatBot
        steps={[
          {
              id: '1',
              message: 'Hello',
              trigger: '2'
          },
          {
              id: '2',
              component: <Example />,
              end: true,
          },
        ]}
      />
```

**Comment by LucasBassetti** [comment]
Hi, I will close this issue but feel free to keep the conversation.

**Comment by Boxplan** [comment]
Thanks Lucas. This issue was not created by me though. Mine is #15. [ Branching some steps into a separate component (#15) ]
