### ISSUE TITLE
Send user's answer to API

### ISSUE THREAD

**Issue by szlaci3** [LucasBassetti/react-simple-chatbot#143]
## Description

How can I send the user's text input to an API? **I want the user to have a conversation with an AI that can receive a message in an API call and respond with a message.** Then display the AI's response message to the user. And let the user type the next question.

The only callback i found is the endCallback, but I want to call a function at every user input, not just one at the end of the conversation.

I have seen what @lackdaz proposed as dynamic chat, but that enables callback for click on the bot's messages or other elements coming from the bot. I can't apply the Component+asMessage logic to the 
user input.

If this is currently not possible with reat-simple-bot, take it as a feature request.

**Comment by LucasBassetti** [comment]
You can create a custom component and call your api there. After receive the message from the api you display it in your custom component. Check [this example](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)

**Comment by Eugen2525** [comment]
I could not make the API call 'inject' the response to the 'message' field inside the steps. Could this be done in the near future?
