### ISSUE TITLE
Custom background Image

### ISSUE THREAD

**Issue by ejuarez1293** [LucasBassetti/react-simple-chatbot#144]
Hello There!

I have been playing around the chatbot and I have been able to connect it to my API, make silly stuff, and whatnot. However, I want to change my background to an image. Is it possible? How is it made?

Thank you!

**Comment by ejuarez1293** [comment]
I am able to change the background color, but every time I change the background it also changes the bubble background color.

**Comment by ejuarez1293** [comment]
Custom avatar icon fails to load on production mode. It appears as avatar

**Comment by ejuarez1293** [comment]
I figure it out. I install the url-loader, configure it like it says here https://webpack.js.org/loaders/url-loader/.
then i did
`import bg from './bg.png`
```
style={{ background: `url("${Bg}")`, }}
```

**Comment by ejuarez1293** [comment]
However, What about changing the icon of the floating chat icon?

**Comment by ejuarez1293** [comment]
Nevermind, I found my way around. I literally remove the svg child and replace it with a new one.

**Comment by AnnaCarolinaWGC** [comment]
Hello, i couldn't reproduce the same positive outcome? I'm still looking for a way to set the background image
