### ISSUE TITLE
is there a way to make the messages from bot multiline?

### ISSUE THREAD

**Issue by sushantshek20** [LucasBassetti/react-simple-chatbot#145]
Chatbot is supposed to ask some objective type question.

Q: Who is the President of USA?
A. Mr. X
B. Mr. Y
C. Mr. Z
D. Mr. O

but with current setup they are converted to a string and all squashed up.

**Comment by LucasBassetti** [comment]
You need use the Option step. Check the example [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/options)
