### ISSUE TITLE
Unable to load ChatBot

### ISSUE THREAD

**Issue by darylfung96** [LucasBassetti/react-simple-chatbot#148]
After installing react-simple-chatbot when I included 
<ChatBot steps={steps} />
into the project it shows a TypeError that this.content is undefined.

**Comment by mnavarromugas** [comment]
I got a different error:

Uncaught TypeError: Cannot read property 'addEventListener' of undefined

**Comment by LucasBassetti** [comment]
I will look into ASAP. Thanks for reporting!

**Comment by RegisSaffi** [comment]
i am getting this error
"TypeError: Cannot read property 'addEventListener' of undefined"

C:/Users/Regis/reactProjects/myapp/node_modules/react-simple-chatbot/dist/react-simple-chatbot.js:379

please help

**Comment by jdb409** [comment]
Hey, 

Any update on this? I'm getting the same error within my create react app.

Thanks!

**Comment by LucasBassetti** [comment]
Please update to version `0.3.8`

**Comment by LucasBassetti** [comment]
Don't `styled-components` v4. Use version 3 or 2.

**Comment by AnirudhaGohokar** [comment]
Even after updating to version 2 or 3, still getting below errors:
Uncaught TypeError: this.content.addEventListener is not a function
Uncaught TypeError: this.content.removeEventListener is not a function

**Comment by SocialAnxty** [comment]
Same issue here and I am using version 3.

Uncaught TypeError: this.content.addEventListener is not a function
Uncaught TypeError: this.content.removeEventListener is not a function
