### ISSUE TITLE
Branching some steps into a separate component

### ISSUE THREAD

**Issue by Boxplan** [LucasBassetti/react-simple-chatbot#15]
@LucasBassetti , this is a very cool project. thanks.

I am trying to branch off some steps into an independent component. For example if SimpleForm is made into a separate component, then i can render that wherever Form is required in the conversation. Can you give some pointers on how to achieve this? I tried to do this with <TextStep> and <Content> but these elements cannot take steps[] . Some guidance or an example to this effect will be of much help.

**Comment by LucasBassetti** [comment]
Hi @Boxplan, I'm glad you liked it!

I don't know if I understand well what you want (sorry for that) but you just need call the id of form that you created if you want. You can check a similar example [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)
