### ISSUE TITLE
Thanks for the update, but it is causing whole app to render nothing on screen after being loaded(like 3 sec)

### ISSUE THREAD

**Issue by RegisSaffi** [LucasBassetti/react-simple-chatbot#150]
## Description

after updating to version 0.3.8
it is being loaded, but after 3 sec, it cause the app to render nothing on screen
and i am checking console for errors and find some like:

TypeError: Cannot read property 'blur' of undefined

Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in t ......

Any help!

## Screenshots

Add screenshots case needes, otherwise delete this section.

**Comment by Sigmus** [comment]
I've just created an example using 0.3.8 and it works: https://codesandbox.io/s/00zvwpmr4n

Can you provide more details and a reproductible example?

**Comment by RegisSaffi** [comment]
i see, but enable user to type and check errors

**Comment by Sigmus** [comment]
Can you update https://codesandbox.io/s/00zvwpmr4n yourself so we can see the errors then?

**Comment by Sigmus** [comment]
You mean you forked it? If so, paste the forked URL here so I can see.

**Comment by RegisSaffi** [comment]
https://codesandbox.io/s/x7yzq2yr9p

here it is,check what's wrong with this

**Comment by mnavarromugas** [comment]
I got Uncaught TypeError: Cannot read property 'focus' of undefined

**Comment by RegisSaffi** [comment]
thanks sir it worked
