### ISSUE TITLE
react-simple-chatbot.js:1 Uncaught TypeError: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by karthikeyana** [LucasBassetti/react-simple-chatbot#151]
## Description
I'm the below issue how to resolve?

## Screenshots
<img width="1438" alt="screen shot 2018-10-27 at 10 49 49 am" src="https://user-images.githubusercontent.com/10651426/47599928-40e86180-d9d6-11e8-8df3-d9bca3c95333.png">

**Comment by LucasBassetti** [comment]
Please use `styled-components` version 2 or 3.

**Comment by ReactGirl** [comment]
Any plans to update to styled-components 4?

**Comment by anujsharmamp** [comment]
I have updated to version 2 and 3 also. But still this error is coming up. 
Hope to see a solution soon.

**Comment by anujsharmamp** [comment]
However found the solution by downgrading "react" and "react-dom " to 16.6.0

**Comment by manojkumar3692** [comment]
Is it possible to make it work without downgrading the react and react dom, And what is the version we have to user styled-components ...

Please help
