### ISSUE TITLE
How to add Objects inside Steps array Dynamically?

### ISSUE THREAD

**Issue by arpit016** [LucasBassetti/react-simple-chatbot#153]
# How to add object inside steps array dynamically?

`this.state =  {steps:[{id: '1', message: 'Hello', trigger:  someFunction}]}
`

Now, 'someFunction' should execute and then update the steps array and then should return the id of new step added, and the steps array becomes:

`let updatedSteps = this.state.steps
 updatedSteps.push({id: '2', message: 'this is the dynamic step', end: true})
 this.setState({steps: updatedSteps})
 return '2'
`

How can this be achieved so that I can add the whole new step object in the steps array of object?

**Comment by LucasBassetti** [comment]
Please check #2

**Comment by hqaisrani-apigarage** [comment]
What @arpit016 was asking is not the same as the thread you mentioned @LucasBassetti. 

@arpit016 I've done some digging around in the source code, and I don't believe that the library is capable of receiving updated steps.

**Comment by vivekhumnabad** [comment]
@hqaisrani-apigarage  can you help me in understanding what have you done to achieve this(Adding steps dynamically through state)
