### ISSUE TITLE
When i use the user: true in the steps getting error. loading and disappearing the chat window

### ISSUE THREAD

**Issue by reactExplorer** [LucasBassetti/react-simple-chatbot#155]
## Description

When i use the user: true in the steps getting error. loading and disappearing the chat window.  When i am not using the user it is good.
following error:
Uncaught TypeError: Cannot read property 'replace' of undefined
    at t.getMessage (react-simple-chatbot.js:1388)
    at t.renderMessage (react-simple-chatbot.js:1401)
    at t.value (react-simple-chatbot.js:1463)
    at finishClassComponent (react-dom.development.js:14306)
    at updateClassComponent (react-dom.development.js:14270)
    at beginWork (react-dom.development.js:15106)
    at performUnitOfWork (react-dom.development.js:17903)
    at workLoop (react-dom.development.js:17944)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at replayUnitOfWork (react-dom.development.js:17224)
    at renderRoot (react-dom.development.js:18037)
    at performWorkOnRoot (react-dom.development.js:18919)
    at performWork (react-dom.development.js:18826)
    at performSyncWork (react-dom.development.js:18799)
    at requestWork (react-dom.development.js:18676)
    at scheduleWork (react-dom.development.js:18480)
    at Object.enqueueSetState (react-dom.development.js:12143)
    at t.o.setState (react-simple-chatbot.js:291)
    at react-simple-chatbot.js:1421
## Screenshots

Add screenshots case needes, otherwise delete this section.

**Comment by LucasBassetti** [comment]
1. What version of the chatbot are you using? 
2. Can you share the code?

**Comment by jonasfresewebdev** [comment]
I'm actually getting the same error message and i've set up the package 2 days ago so it is the newest version.
Seems to be a package problem which appears when you use **user: true**

**Comment by LucasBassetti** [comment]
Are you using the `user: true` as the first step?

**Comment by jonasfresewebdev** [comment]
As the second like in your documentation 
...`{
      id: '2',
      user: true,
      trigger: '3',
    },`...

**Comment by reactExplorer** [comment]
yes i am also using latest react-simple-chatbot": "^0.4.0",  "react-dom": "^16.6.0",..

**Comment by LucasBassetti** [comment]
Please try version `0.4.1`

**Comment by reactExplorer** [comment]
LucasBassetti thanks for your quick response.

I tried with the new code. now chat is not disappearing  but the text box is not ready to take the text and next steps are executing. Also in internet explorer the chat not displaying and getting the following error.IN Chrome i don't see any error.

SCRIPT438: Object doesn't support property or method 'assign'
0.chunk.js (30482,89)
SCRIPT5009: 'Promise' is undefined
0.chunk.js (27394,9)
SCRIPT438: Object doesn't support property or method 'assign'
0.chunk.js (24754,9)
SCRIPT5009: 'Promise' is undefined
0.chunk.js (27394,9)

**Comment by LucasBassetti** [comment]
This error is just on IE? Unfortunately I don't think this will work on IE.

**Comment by reactExplorer** [comment]
but in chrome/Edge the user input is not taking.

**Comment by LucasBassetti** [comment]
Can you send me the code (your steps, your package.json file, etc.)?

**Comment by reactExplorer** [comment]
//App.js file 

import React, { Component } from 'react';
import Chat from './Chatbot/Chat';

class App extends Component {
  
  state = {
    steps: [
      {
        id: 'hi',
        message: 'welcom to simple chatbot ',
        trigger:'1',
      },
      {
        id: '1',
        message: 'welcom to simple chatbot ',
        trigger: '2',
      },
      {
        id: '2',
        message: 'Hi, nice to meet you, { previousValue }',
        trigger: '3',
      },
      {
        id: '3',
        message: 'I am in last step',
        end: true,
      },
    ],
    theme: {
      background: '#f5ffff',
      fontFamily: 'Helvetica Neue',
      headerBgColor: '#EF6C00',
      headerFontColor: '#fff',
      headerFontSize: '15px',
      botBubbleColor: '#EF6C00',
      botFontColor: '#fff',
      userBubbleColor: '#fff',
      userFontColor: '#4a4a4a',
    },
  }

  render() {
    return (
      <div className="App">
        <Chat theme={this.state.theme}  steps={this.state.steps}></Chat>
      </div>
    );
  }
}

export default App;

**Comment by reactExplorer** [comment]
//Chat.js file

import React from 'react';
import ChatBot from 'react-simple-chatbot';
import { ThemeProvider } from 'styled-components';

const chat = (chat) => {
  return (
    <div>
      <ThemeProvider theme={chat.theme}>
        <ChatBot floating="true" headerTitle="virtual helper" steps={chat.steps} />
      </ThemeProvider>
    </div>
  );
}
export default chat;

**Comment by reactExplorer** [comment]
//package.json file

{
  "name": "chatbot",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-scripts": "2.1.1",
    "react-simple-chatbot": "^0.4.1",
    "styled-components": "^4.0.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

**Comment by LucasBassetti** [comment]
Please use `styled-components` version 2 or 3

**Comment by LucasBassetti** [comment]
don't use user input as first

**Comment by reactExplorer** [comment]
it worked.. thanks a lot for your time. chatbot is a nice  feature to have in the website. In the process of learning reactJs i came across this.

**Comment by Milos5611** [comment]
I have a weird issue which seams similar. 
If i create file with steps and include it => add to <ChatBot steps={xxx} /> component all works good.
If i add array of steps to component directly it throw `Cannot read property 'options' of undefined ` but sometime `Cannot read property 'message' of undefined`...not sure what is the problem.
