### ISSUE TITLE
How to set the proper dimensions when embedding the chat bot on Wordpress site using iFrame?

### ISSUE THREAD

**Issue by GilbertMizrahi** [LucasBassetti/react-simple-chatbot#156]
I have created a chatbot 
http://advanced-algorithms.com/ConversationalUI/

It works fine. However, I want to embed it on a Wordpress site and I want the page to show the header (WP) and then the chatbot should use the rest of the horizontal area. It should look similar to what I have when not embedded.

this is the result after embedding
http://twnelwebsite.azurewebsites.net/conversationalui/

Probably a simple CSS thing, but I haven't been able to figure it out.

Someone has dealt with something similar? How did you solve it?

**Comment by LucasBassetti** [comment]
You can try use `min-height: calc(100vh - 80px);` in your iframe component

**Comment by GilbertMizrahi** [comment]
That works. Thanks.
