### ISSUE TITLE
"Can't resolve styled-components in ...\node_modules\react-simple-chatbot\dist"

### ISSUE THREAD

**Issue by jkhaui** [LucasBassetti/react-simple-chatbot#157]
Hey,

Sorry if I'm making a basic mistake, but the chatbot fails to build due to being unable to resolve styled-components. Any tips for how to fix this?

Cheers,
Jordan

**Comment by LucasBassetti** [comment]
What version of the chatbot are you using?

Did you install the `styled-components`. Please use version 2 or 3

**Comment by jkhaui** [comment]
It works now, sorry. Great job. I just didn't install styled-components properly before, stupid me

**Comment by AnirudhaGohokar** [comment]
Hey Lucas,
First of all thanks for this amazing chatbot!
Our project doesn't use styled-component so dont want to install this extra dependency. Is there any way we can get around this?
