### ISSUE TITLE
Question Answering

### ISSUE THREAD

**Issue by malikkamranabid** [LucasBassetti/react-simple-chatbot#158]
**I want user to question chat bot and then chat bot look into steps to find relevant answer then user can again ask another question and chat bot return another answer**
It is possible if yes then I am looking for example. Can  you give me ?

**Comment by sazzad24x7** [comment]
It's already in the documentation. Customize it in your way.
https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia
