### ISSUE TITLE
Cant use the library on react SSR

### ISSUE THREAD

**Issue by ashmitaggarwal** [LucasBassetti/react-simple-chatbot#164]
window not defined error and styledcomponent is mandatory if i dont want to use this library..

please help

**Comment by LucasBassetti** [comment]
Hi,

I don't have experience with SSR but maybe [this link](https://github.com/reactjs/react-chartjs/issues/57#issuecomment-257117560) can help you.

**Comment by ashmitaggarwal** [comment]
by default bot is in open state.. how to enable toggle button for it..

**Comment by vldmir** [comment]
> by default bot is in open state.. how to enable toggle button for it..

Hi,
You need add  floating={true} property 

<ChatBot floating={true} />
