### ISSUE TITLE
Trigger step change from outside of chatbot component

### ISSUE THREAD

**Issue by m-grzybek-first10** [LucasBassetti/react-simple-chatbot#166]
Hi @LucasBassetti , great job on the chatbot! 
I do have a question though. I'm implementing this chatbot, and I need to have a button, that can trigger a change of the current step. Specifically go back in history. Is there a way to trigger that from outside of component?

**Comment by LucasBassetti** [comment]
Hey @m-grzybek-first10,

Not sure if you can do that. I believe a way that can work is create an event listener in a custom component and use it to catch some data from outside of the component.

**Comment by m-grzybek-first10** [comment]
Hey @LucasBassetti, thanks for the info, unfortunately, we had to move to something more customizable, we need a really flexible solution for our current project. But, great stuff anyway, thank you :)

**Comment by m-grzybek-first10** [comment]
Closing as nor longer relevant
