### ISSUE TITLE
Examples of inputAttributes and metadata objects in the steps?

### ISSUE THREAD

**Issue by GilbertMizrahi** [LucasBassetti/react-simple-chatbot#168]
Are there any examples of how to use the inputAttributes and metadata objects in the steps?

That would be helpful for more advanced applications.

**Comment by LucasBassetti** [comment]
You can find some example in #119

**Comment by GilbertMizrahi** [comment]
Great. Thanks. 
That covers the inputAttributes. Any examples for the metadata obejcts?
