### ISSUE TITLE
Is there anyway to have steps paused until a button is pressed?

### ISSUE THREAD

**Issue by footballdaddy** [LucasBassetti/react-simple-chatbot#17]
For normal text they will go through be shown immediately after another text and will display the loading animation. I am wondering if there is a way, other than options, to make it not continue until a button is pressed (outside the chatbox)

**Comment by LucasBassetti** [comment]
Hi @footballdaddy,

No, you can just do it inside the chatbox using [Custom Components](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component).

You need define a custom step and set `waitAction` prop as `true`. After that, you need call the `triggerNextStep` callback to call another step.

You can check a example [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)
