### ISSUE TITLE
How to pass state between custom components?

### ISSUE THREAD

**Issue by luigib07** [LucasBassetti/react-simple-chatbot#170]
Hi, is there an example on how to pass state from one custom component to another? 
I can do this normally by passing the state from thisComponent to NextComponent via the render, but I want to show NextComponent as a separate message in the chatbot when triggerNextStep is called.
I tried using

 this.props.triggerNextStep({
      value: this.state.objectArr,
      trigger: nextComponent
    });

after a button click in thisComponent to go to the next custom component(shown below) and pass the value. I do not see the value when I check the console.log for this.props.steps in the next component, only the id of the previous component.

I also tried passing in the state in the steps via
<Chatbot steps={
{
id: "1",
message:"Example",
trigger:2
},
id: "2",
user:true,
trigger: "3"
{
id: "3",
component: (thisComponent />),
asMessage:true,
trigger: "2"
},
{
id: "4",
component: (NextComponent someState={this.state.object} />,)
asMessage:true,
trigger: "2"
}
]
/>

NextComponent is not getting the updated state value and is showing an empty array in the console log. If I move NextComponent outside of the chatbot component, it renders properly.

**Comment by LucasBassetti** [comment]
You can't use state but custom components receive a prop [steps](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component) with all steps rendered by the chat that you can use the get their values inside the component.
