### ISSUE TITLE
Gatsby build - Building static HTML for pages failed... WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ashokballolli** [LucasBassetti/react-simple-chatbot#172]
**Describe the bug**
New to these technologies, need help to fix this issue.
When i do gatsby build i am getting this error
Building static HTML for pages failed... WebpackError: ReferenceError: window is not defined

Read the previous discussions here, still not able to fix.

```
const chatbottest2 = ({ data, location }) => {
    return (
        <>
            <MetaData
                data={data}
                location={location}
                type="website"
                title="Chat Bot"
            />
            <Layout headerDividerStyle="shadow">
                        <SimpleForm>
                        </SimpleForm>
            </Layout>
        </>
    )
}
```

```
class SimpleForm extends Component {
render() {
return (

  <ChatBot
    headerTitle="Speech Recognition"
    recognitionEnable={true}
    steps={...}
    width="100%"
  />
);
}
}
```

react and react-dom are of version 16.5.2.

Thanks in advance.

**Comment by LucasBassetti** [comment]
Are you using `react-static`? Please take a look [here](https://github.com/nozzle/react-static/issues/16)

**Comment by ashokballolli** [comment]
Thank you very much, I have fixed that issue. And also thank you very much for "react-simple-chatbot".
