### ISSUE TITLE
UglifyJs Unexpected token: keyword (const)

### ISSUE THREAD

**Issue by dotmaike** [LucasBassetti/react-simple-chatbot#175]
**Describe the bug**
Avoid future issues with uglifyjs-webpack-plugin

**Additional context**
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362

**Solution**
https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by pascalgagneur** [comment]
Switched to terser (https://github.com/LucasBassetti/react-simple-chatbot/pull/200)

@LucasBassetti I think you can closed this
