### ISSUE TITLE
CircularJSON deprecated

### ISSUE THREAD

**Issue by dotmaike** [LucasBassetti/react-simple-chatbot#176]
**Describe the bug**
This package has been deprecated

**Additional context**
https://www.npmjs.com/package/circular-json

**Comment by pascalgagneur** [comment]
By using flatted instead of CircularJSON, the chatbot won't be able to read old cache from localStorage.

I've started on a branch containing fixes to handle parse errors.

https://github.com/pascalgagneur/react-simple-chatbot/tree/Upgrade-CircularJSON-to-flatted

**Comment by pascalgagneur** [comment]
@LucasBassetti 👆

**Comment by LucasBassetti** [comment]
Go ahead 👍

**Comment by pascalgagneur** [comment]
@LucasBassetti time to close this?
