### ISSUE TITLE
[Enhancement] Remove option repeating user message.

### ISSUE THREAD

**Issue by footballdaddy** [LucasBassetti/react-simple-chatbot#19]
I am trying to implement a feature I can use if (currentStep.options && data) in ChatBot.jsx to remove repeating to the option as a user and not directing sending the to trigger message. I tried deleting if statements and parts of it. But I am unable to achieve the desired effect.

**Comment by LucasBassetti** [comment]
Hi, 

Sorry but I didn't understand this problem. Can you provide more details?

**Comment by footballdaddy** [comment]
I decided that it would be best to leave as it is. THanks for the consideration though.
