### ISSUE TITLE
Clear all steps

### ISSUE THREAD

**Issue by deepak-mohanty** [LucasBassetti/react-simple-chatbot#193]
Hi,

I want to clear all the steps after a button triggers. Is there any option to clear all the steps at once?

**Comment by SabaRathnamK** [comment]
Same issue.. Is there any way or option to reset or clear the existing conversation?

**Comment by ShuaibMalik786** [comment]
I want to clear the chat by triggering a button. I tried by updating the state as empty, but it didn't affect the conversation. I need help...

**Comment by LucasBassetti** [comment]
You can try refresh the component. Like:

```
handleClear = () => {
  this.setState({ clear: true }, () => {
    this.setState({ clear: false });
  });
}

render() {
  return this.state.clear ? <div /> : <ChatBot steps={steps} />;
}
```

**Comment by pascalgagneur** [comment]
By changing key on the component, react is forced to create a new instance of the ChatBot
```js
handleClear = () => {
  this.setState({ chatbotKey: (unique key) };
}

render() {
 <ChatBot key={this.state.chatbotKey} steps={steps} />;
}
```

https://medium.com/@albertogasparin/forcing-state-reset-on-a-react-component-by-using-the-key-prop-14b36cd7448e

**Comment by fdstevex** [comment]
@pascalgagneur Did that work for you?  I'm trying to use the key property to cause a reset with a new list of steps, but I get an exception thrown 'TypeError: undefined is not an object (evaluating 'v.message')' @ react-simple-chatbot.js:2012

**Comment by pascalgagneur** [comment]
Hi
Don't know if you enabled cache. You can't use cache with a new set of
steps. Pascal
