### ISSUE TITLE
[Help] Creating a close button in chat ui

### ISSUE THREAD

**Issue by footballdaddy** [LucasBassetti/react-simple-chatbot#20]
So I have been modifying around to create this.
I believe you have to be inside a step to be able to render (w/ previous, and trigger)

Creating a button like on chatbot.js 
`            <button onClick={() => this.triggerB}>Continue</button>
  triggerB() {
    this.triggerNextStep();
  }
`

it seems to me the only way to do this is by using redux to have the data pass up, however, if there an alternative or an idea I would appreciate some input.

**Comment by LucasBassetti** [comment]
Would you like a button to trigger the next step? I don't intend to create it. I recommend you look the [Custom Component](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component). You can use the `waitAction` prop and create a button to trigger next step (using `triggerNextStep` callback` when user clicks.

**Comment by footballdaddy** [comment]
Alright, understandable.
