### ISSUE TITLE
[Help] Save messages rendered

### ISSUE THREAD

**Issue by juanmndz** [LucasBassetti/react-simple-chatbot#21]
I am trying to figure out a way to save the messages, so the rendersteps are cached and when user come back they are exactly back where they were.

**Comment by LucasBassetti** [comment]
Hi, unfortunately there is no support for cache the rendered steps yet. Maybe I can implement something with `localStorage` in a future release.

**Comment by juanmndz** [comment]
Care to explain part of the process to do this? Maybe, I can help with the right push?

**Comment by LucasBassetti** [comment]
Cache added in `0.2.3`. Please update your package and use the `cache={true}` prop. The cache will be clean automatically when you get the final step or you can do it manually using `localStorage.removeItem('rsc_cache');`
