### ISSUE TITLE
[Error] Converting circular structure to JSON 

### ISSUE THREAD

**Issue by juanmndz** [LucasBassetti/react-simple-chatbot#22]
Thanks for the inclusion of the cache prop. There is one issue though cache prop with custom components.

Whenever using custom components you will get an error 'Converting circular structure to JSON', tried it on all examples with custom components and got same error
![chat](https://user-images.githubusercontent.com/16310386/29238340-4207dfc2-7ee8-11e7-9108-b7ef28a8c893.png)
,

**Comment by niksmac** [comment]
How can we reproduce this?

**Comment by juanmndz** [comment]
It happens whenever you use any custom component with the cache prop as true.

**Comment by LucasBassetti** [comment]
Fixed in `0.2.4`. Thanks for reporting!
