### ISSUE TITLE
Full size not auto scrollable on mobile ?

### ISSUE THREAD

**Issue by rianfloo** [LucasBassetti/react-simple-chatbot#23]
Hello Lucas!

Thanks for your amazing react chatbot!

I tried to put a 100vh heigh on mobile to display the chatbot window but when a new component is rendered, there is no auto scrolling :( 

Any solution ?

Best,
Florian

**Comment by LucasBassetti** [comment]
Hi @rianfloo, Thanks for like it!

Can you provide more details (OS, browser, ...) that you using?

Here is working normally (safari and chrome, iOS)

**Comment by LucasBassetti** [comment]
Hi, I will close this issue but feel free to keep the conversation.
