### ISSUE TITLE
how can I integrate the chat onto RSC/Intercom widget?

### ISSUE THREAD

**Issue by abhinav118** [LucasBassetti/react-simple-chatbot#24]
Hey Lucas, Love the react chat. Would love to contribute to RSC chat widget. Is that part of the repo yet? 💌

**Comment by LucasBassetti** [comment]
Hi, thanks!! :)

Sorry, what widget are you talking about?

**Comment by abhinav118** [comment]
The intercom like widget at the bottom of documentation page:
https://lucasbassetti.com.br/react-simple-chatbot/#/docs/installation

**Comment by LucasBassetti** [comment]
Are you talking about this?
![image](https://user-images.githubusercontent.com/1014326/29483870-448c68b2-8488-11e7-99cd-fc966f6d9704.png)

**Comment by abhinav118** [comment]
Exactly

**Comment by LucasBassetti** [comment]
You just need use the floating prop to do that. Like this:
```
<ChatBot
  steps={steps}
  floating={true}
/>
```

**Comment by abhinav118** [comment]
Ok is there extra documentation regarding this?

**Comment by LucasBassetti** [comment]
You can find the ChatBot props [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot)

**Comment by abhinav118** [comment]
Ok cool. Thanks a ton! Also is the rest chatbot  compatible with react
native world? Have you tried it? If so can you share examples.

Very interested in react native

**Comment by LucasBassetti** [comment]
My pleasure!

I started the react native project but I didn't finish it yet ( I need find some time to it :| )

You can check it [here](https://github.com/LucasBassetti/react-native-chatbot)

**Comment by abhinav118** [comment]
Cool any ETA on the completion. Having notifications inside chatbot would
be cool.

**Comment by LucasBassetti** [comment]
No prevision yet (sorry). How would this notification work?

**Comment by abhinav118** [comment]
It will be chatbot notifications which help users interact better and
engage with services that chat bot would work silently and be more
responsive. Especially for sake of security, it's better we have a
specialized floater widget
 or native app

**Comment by abhinav118** [comment]
Hey Lucas,

How's you?

I am Abhinav, CEO of Joy up. I wanted to chat about an opportunity with our
startup http://JoyUp.me

We are planning to create an react native app for joyup as a mobile app
chatbot, possibly a 50k business owner app downloads market by end of 2018.

Are you open to any future opportunities for 2018Q1?

Thanks
Abhinav

**Comment by LucasBassetti** [comment]
Hi @abhinav118 

I sent a message for your gmail
