### ISSUE TITLE
Doesn't 100% width on mobile

### ISSUE THREAD

**Issue by PSheon** [LucasBassetti/react-simple-chatbot#25]
Hi Lucas, thank you first, here is my question, i'm using node 8.1.4 and latest chrome
and my Dialog box did not 100% width on mobile user
I hope you can answer for me : )

<img width="630" alt="default" src="https://user-images.githubusercontent.com/20603727/29502206-dd4fba7a-8660-11e7-8cdc-6e682fc63adf.PNG">
<img width="321" alt="1" src="https://user-images.githubusercontent.com/20603727/29502207-dd52e970-8660-11e7-9999-e2c26b80805f.PNG">

**Comment by LucasBassetti** [comment]
Hi @PSheon,

Thanks for reporting! Can you inspect the element and check if the `@media` prop is being applied? Like that:

![image](https://user-images.githubusercontent.com/1014326/29502347-a54bee6a-8605-11e7-9de8-f803ffe924d5.png)

Did you test in a real mobile?

**Comment by LucasBassetti** [comment]
Can you try to use the `floating` prop? Just to check if will work. Like that:

```
<ChatBot
  floating={true}
  steps={steps}
/>
```

**Comment by PSheon** [comment]
It's wired, everything is ok when i using `create-react-app`,
but it doesn't work in my project
Will my `webpack.config.js` be the problem?
<img width="494" alt="default" src="https://user-images.githubusercontent.com/20603727/29504357-b3d67362-8671-11e7-8b68-f02b763d785f.PNG">

**Comment by LucasBassetti** [comment]
Did you install the `styled-components` peer dependency?

**Comment by LucasBassetti** [comment]
Maybe is a viewport issue. Try to add this line of code in your `head` tag in the html file
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by PSheon** [comment]
Always forget the basic things..HAHA

**Comment by LucasBassetti** [comment]
this happens with me sometimes too hahahahah
