### ISSUE TITLE
How to 'inject' ajax call into 'message' ?

### ISSUE THREAD

**Issue by Eugen2525** [LucasBassetti/react-simple-chatbot#265]
The question is:
How to 'inject' ajax call into 'message' ? or put another way, how to make the bot make an ajax call taking the user input and display the result?

If we create a custom component, like the Wikipedia example, the result is rendered as a separate `<div>` element, but I want the result to appear from the bot.

Can this be done?

**Comment by pascalgagneur** [comment]
You can't. The steps prop is kept as a state, you can't update steps.

**Comment by Eugen2525** [comment]
Ok, I got the workaround for this somehow. (use "asMessage" from the api and some hand engineering)

**Comment by Ziad-ElAlaily** [comment]
Hey @Eugen2525 , I know this is old but can you share your hand engineering if possible?
