### ISSUE TITLE
Is there any way where I can send a static message from user using user: true?

### ISSUE THREAD

**Issue by Praj-akta** [LucasBassetti/react-simple-chatbot#267]
I wanted to try a demo conversation of chatbot and user and I just wanted to show static data for a while. 
So I was wondering if I can send a static message from user's end without using user: true( means user cannot type) just wanted to show that this message is from user on the right side.

My expectation is that if i'll give human: true or user: true then it should send the message from user's side rather than user typing it.

Can this be possible ? I'm just trying to do this and read all your documentation but I had this doubt. Please Help!

![Screenshot from 2020-04-10 18-14-51](https://user-images.githubusercontent.com/55618783/78991947-cd99c780-7b57-11ea-8145-e65354715ca7.jpg)
Like this.

**Comment by Jaikant** [comment]
@Praj-akta I was wondering the same, did you figure anything out?

**Comment by barth-loumi** [comment]
@Praj-akta @Jaikant I'm having the same issue, did you come up with a solution?

**Comment by Praj-akta** [comment]
@Jaikant not yet

**Comment by Praj-akta** [comment]
@barth-loumi Not yet

**Comment by tahereshamimi** [comment]
i have this problem, i want to show previous message that get from server, how should i do this?
