### ISSUE TITLE
Get source code of the tutorial chatbot hosted at https://lucasbassetti.com.br/react-simple-chatbot

### ISSUE THREAD

**Issue by navneet-g** [LucasBassetti/react-simple-chatbot#272]
**Describe the bug**
I am building a chatbot similar to tutorial bot hosted at https://lucasbassetti.com.br/react-simple-chatbot, can you release the source code of that bot?

**Comment by AkshraGupta** [comment]
I want that too! Specially the redirect to another webpage step. Would be a huge help, thanks!

**Comment by matheus-garcia** [comment]
+1 @LucasBassetti

**Comment by rishinandan08** [comment]
> I want that too! Specially the redirect to another webpage step. Would be a huge help, thanks!

+1 @LucasBassetti

**Comment by LucasBassetti** [comment]
The source code of the website is here: [https://github.com/LucasBassetti/react-simple-chatbot/tree/gh-pages](https://github.com/LucasBassetti/react-simple-chatbot/tree/gh-pages)
