### ISSUE TITLE
Error : 'ChatBot' is declared but its value is never read

### ISSUE THREAD

**Issue by AnirupPat** [LucasBassetti/react-simple-chatbot#279]
**Description** : Could not find a declaration file for module 'react-simple-chatbot'. '/Users/anirup.patnaik/Documents/Workspace/Virtual Labs/react-native/medi-share/node_modules/react-simple-chatbot/dist/react-simple-chatbot.js' implicitly has an 'any' type.
  Try `npm install @types/react-simple-chatbot` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-simple-chatbot';

this error is because of this line:
import ChatBot from 'react-simple-chatbot';

Package.json:
"dependencies": {
"react-simple-chatbot": "^0.6.1"
}

**Comment by josan84** [comment]
What was the solution for this error?

**Comment by sarvan2research** [comment]
@AnirupPat  how did you fixed above issue. Am new to front end development skill, Stuck in above error while start using react-chat-bot. Thanks in advance.
