### ISSUE TITLE
i want to hide password  when after user input it but , hideInput prop is not working

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [LucasBassetti/react-simple-chatbot#285]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by giancarlobianchi12** [comment]
Could you solve it ?

**Comment by CHANDRAMOHANnegi** [comment]
Yes
