### ISSUE TITLE
Complete setup steps

### ISSUE THREAD

**Issue by Instagit** [LucasBassetti/react-simple-chatbot#3]
Hi,
this project looks interesting. I've worked with node before, but not with all the tools this project uses. Can you give a complete list of setup steps to get it working?

1. git clone https://github.com/LucasBassetti/react-simple-chatbot.git
2. change "name" in package.json (npm can't install a package with the same name as the project)
3. npm install
4. npm install react-simple-chatbot --save

Now all tests are passing (npm test), but when running npm start I get

````
ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' /home/test/Desktop/react-simple-chatbot/app/js/main in /home/test/Desktop/react-simple-chatbot
 @ multi main
webpack: Failed to compile.
````

How do I make the server work? Where to put the [example files](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/previous-value) and how to name them?

**Comment by LucasBassetti** [comment]
Hi,

You don't need clone the repository and there is no server. You need some react project to use that.

You can use this ([react boilerplate example](https://github.com/LucasBassetti/react-airbnb-boilerplate)) for create a sever and install the chatbot. 

After clone this boilerplate you can install de chatbot using the command:

`npm install react-simple-chatbot --save`

After installed, you can import the chatbot in your project using the command:

`import ChatBot from 'react-simple-chatbot';`

After import, you can call the chatbot component in your jsx/js file. Like [this example](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/bmi)

**Comment by Instagit** [comment]
Cool, it works. Thanks!

**Comment by AlexanderIgnacz** [comment]
Hi, @LucasBassetti 
Are you around?
