### ISSUE TITLE
Trigger function user input, return find to next step using async/await

### ISSUE THREAD

**Issue by ancs21** [LucasBassetti/react-simple-chatbot#31]
Dear Lucas,
I have idea so.
When user input, trigger function process return other value in next steps.
Example:
``` javascript

const steps = [
  {
    id: '0',
    message: 'Welcome to react chatbot!',
    trigger: '1',
  },{
    id: '1',
    user: true,

    trigger: async ({value, steps}) => await hello({value, steps}), // return 'hello' or 'thanks'

  }, {
    id: 'hello',
    message: 'Bye'
  }, {
    id: 'thanks',
    message: 'Thanks',
  }
];

```

**Comment by LucasBassetti** [comment]
Sorry, I didn't understand. Are you suggesting a new feature? 

In async situation you can use the [Custom Step](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps) with `waitAction` prop. So, you will receive the [triggerNextStep](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component) prop that you can use to trigger your next step.

**Comment by ancs21** [comment]
Nice. I understand. Thanks.
