### ISSUE TITLE
How to integrate with wit.ai or api.ai ?

### ISSUE THREAD

**Issue by rishabhsethi29** [LucasBassetti/react-simple-chatbot#32]
Thanks for such a nice UI first.

I would like to know.
Is steps can only be pre-defined or they can be dynamic.
Because,that's how a real life chatbot will be made,on a nlp platform.
But,I have tried updating state assigned to step props.But,It doesn't update the conversation.
A good example for dynamic Steps would be great.

**Comment by LucasBassetti** [comment]
Hi,

Steps must be pre-defined. You can make a dynamic situation triggering different step based on user actions but the steps can be pre-defined. 

To create steps more dynamic you can use:
1. [Custom Step](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps) with `waitAction={true}`. So, you will be able to trigger a step based in user actions using the [triggerNextStep](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component) prop.
2. Using [trigger](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps) step prop as function. So, you will be able to trigger a step based in the value received in the function. Like that:
```
{
  id: '2',
  message: ({ previousValue, steps }) => 'Hello',
  trigger: ({ value, steps }) => value === 'Hi' ? '3' : '4',
},
```

I never use these bot apis (wit.ai and api.ai) but the idea of this project is some more simple, like a help support for example (without databases, machine learning, etc).

I hope this could help you!

**Comment by Milos5611** [comment]
Hi @LucasBassetti ,

I have a problem with this approach, in triggerNextStep a do 
`props.triggerNextStep({value:` "Yes",trigger: 3'})}` and step 3 is fired but value is not there on first fire, only on second and so on. I couldn't find similar problem opened.

And also, is there any way to customise user response component ? 
Like, i want to show something diferent when user chose option or type something ?
Any example, reource, guide... ???
