### ISSUE TITLE
Are there any way to response the value on User Side from Custom Component! 

### ISSUE THREAD

**Issue by gordongordon** [LucasBassetti/react-simple-chatbot#33]
hi, Lucas

thx for the great works!  I am using "react-simple-chatbot": "^0.2.6",
I have been look over the api , are there any way to response the value as user input by    
```
 this.setState({ trigger: true }, () => {
       this.props.triggerNextStep( { value: value });
     });
```

1. Since, I created my custom option component, by select a value,  even thought, I return by triggerNextStep! It wasn't displayed as user input in Step #3!  e.g. when i inputed my name in Step#1, my name got display on the right!  

2. And also, couldn't find a way to display the SubmitButton. (note: even set is as hideSubmitButton="false"
 
![p1](https://user-images.githubusercontent.com/21987380/30649051-23797c26-9e52-11e7-89e0-d3f73d7ac441.jpeg)
![p2](https://user-images.githubusercontent.com/21987380/30649052-237a17da-9e52-11e7-9fec-df9bdb3b8a9c.jpeg)
![p3](https://user-images.githubusercontent.com/21987380/30649050-2378a256-9e52-11e7-9718-8c80acc9e11b.jpeg)

bye now!

**Comment by LucasBassetti** [comment]
Hi @gordongordon, thanks for enjoy it!

1. Indeed. Technically when you use a custom component with `waitAction` is a user input but without render as message. As you are using a custom component you can replace the content with the option selected by the user. I will considering implement in a next release a option to render this result as user message.

2. Thanks for reporting! I need to check it. Are you testing in mac and iOS?

**Comment by gordongordon** [comment]
I am writing the program in Windows 10!  It is a web app!  I test in most browsers!  thx !

**Comment by LucasBassetti** [comment]
The submit button appear in some browser?

**Comment by gordongordon** [comment]
no, non of them!

**Comment by LucasBassetti** [comment]
Strange. Is your code open-source? Can I have access to it?

**Comment by gordongordon** [comment]
No,it is not a open-source! Just my little webapp. Yes, you can access it! in order to save your time! here is some details! 
I disable most of codes! So, then you can test it!  
the main program is under src/index.js
chatbot is under src/components/chatbot/formSaleChatbot (this is the demo)
Run: node server.js (localhost:3000)
Compile: webpack
[My Github link](https://github.com/gordongordon/hom)
Thx!

**Comment by LucasBassetti** [comment]
Did you run `npm run build` before test?

I recommend you use the `webpack-dev-server` to watch your changes instead to build the app for all change that you make.

Take a look in this [boilerplate](https://github.com/LucasBassetti/react-airbnb-boilerplate)

**Comment by gordongordon** [comment]
Just did that, what you told me!  I run "npm run build",  the chatbot is running , but no submitbutton! 
I also add webpack-dev-server is running, but no submitbutton!

note: webpack: Compiled successfully.

![whatsapp image 2017-09-22 at 1 33 02 am](https://user-images.githubusercontent.com/21987380/30709851-32204bb2-9f36-11e7-9f07-2821175c730e.jpeg)

**Comment by LucasBassetti** [comment]
Try to change:

`import FormSaleChatbot from 'chatbot/formSaleChatbot'` 
to
`import FormSaleChatbot from './components/chatbot/formSaleChatbot'`

and 

`hideSubmitButton="false"`
to
`hideSubmitButton={false}`

1. stop server
2. run `npm run build`
3. run `npm start agatin`

**Comment by gordongordon** [comment]
Yes, I done that without and error! But the button is still hiding!   I think, I will try to use your airbnb boilerplate tomorrow!  and add chatbot!  Will get back to you!  Thx for your great support!

**Comment by LucasBassetti** [comment]
Strange. I done it here and works.

![image](https://user-images.githubusercontent.com/1014326/30713052-715a6fb2-9ee4-11e7-9fe0-cb39c63a3c6a.png)

**Comment by gordongordon** [comment]
Haha! What version of node are U using?

**Comment by gordongordon** [comment]
I did update npm, node, webpack, but do n't solve the problem!  I finally download the source from my Githut.  and compiled it locally, it worked!   Anyway, thx for your support! 

Beside that, you is your goal for this project, sine lots of chatbot out there, such as botpress.io?

**Comment by senky** [comment]
@LucasBassetti 
> I will considering implement in a next release a option to render this result as user message.

Is this option already implemented? I would really make good use of it. :)

**Comment by LucasBassetti** [comment]
@senky not yet. Feel free to do that 👍

**Comment by grahamd711** [comment]
hi @LucasBassetti do you have any plans of implementing the custom component on the user response side? awesome work with this project!

**Comment by dgg32** [comment]
Hi, same question, how to set the "value" prop in the "input" element from external please? There is no API from the chatbot so I can't transfer the new value to it unless I pressed a key on my keyboard. I tried dispatch a keypress event to no avail.
<img width="1183" alt="Bildschirmfoto 2022-03-18 um 12 28 05" src="https://user-images.githubusercontent.com/1873196/158937760-23b2beb0-2ea9-491b-9c07-a8b94975a4c8.png">
