### ISSUE TITLE
Uncaught TypeError: this.updater.enqueueCallback is not a function. Example seems stuck at "asking for user input", but has input box greyed out.

### ISSUE THREAD

**Issue by davidfufu** [LucasBassetti/react-simple-chatbot#34]
React: "react": "^16.0.0",
Node: v8.4.0
NPM 5.4.2

My steps are: 

1.  create react app
2. npm run start
2. create separate file for BMI component example
3. import BMI component into app.js
4. go to localhost 3000

The development server starts and I go to local host 3000. This is what I see. 
![alt text](https://i.imgur.com/o2tNG28.png)

My code is below. Basically just create react app with the BMI component.

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import ChatBot from 'react-simple-chatbot';
import BMIExample from './BMIExample';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <BMIExample/>
      </div>
    );
  }
}

export default App;
```

The error I get my browser is : 
```
react-simple-chatbot.js:1 Uncaught TypeError: this.updater.enqueueCallback is not a function
    at t.r.setState (react-simple-chatbot.js:1)
    at react-simple-chatbot.js:1
```

**Comment by davidfufu** [comment]
Hmm. Changing the versions of react and react dom to:
 "react": "15.6.1",
    "react-dom": "15.6.1",

from the default create react app:
 "react": "16.0.0",
    "react-dom": "16.0.0",

seemed to have fixed it.

**Comment by LucasBassetti** [comment]
Hi, I will try to figure out this compatibility with react 16.

Thanks for reporting!
