### ISSUE TITLE
Any way to trigger a step from user text input?

### ISSUE THREAD

**Issue by davidfufu** [LucasBassetti/react-simple-chatbot#36]
I only see examples for triggers steps based on clicking on buttons in the options example. Is there a way trigger different steps based on the value of the "user: true" response ?

For example, can something like this be done? here's what I'm thinking in rough pseudo code.

```
if ({previousValue} === "yes") {
     trigger("2");
}
```

**Comment by davidfufu** [comment]
Just read the API. Please correct me if I'm wrong, but it would be implemented like this no?
```
{
  id: '1',
  user: true,
  trigger: ({ value, steps }) => {
      if (value === "yes"){return "2"}
      else { return "3"}
  }
}
```

For the trigger function, what are the arguments that it can take? I'm unclear on what steps is. I'm assuming value would be the value that the "user: true" would take from the user.

**Comment by LucasBassetti** [comment]
Hi! Yes, you can implement this. 

The `value` is the user input and the `steps` is all steps already showed. Try to put a `console.log(steps)` in trigger function that you can see the result.
