### ISSUE TITLE
getting duplicated text

### ISSUE THREAD

**Issue by IbrahimLakhzine** [LucasBassetti/react-simple-chatbot#361]
I am getting duplicates text when using options

this is the steps I have used:

const steps=[
    {
      id: '1',
      message: 'Those Are The Services That I am offering ,Please Choose A Service?',
      trigger: '2',
    },
    {
      id: '2',
       options: [
         {value:"Web Developement" , label: 'Web Developement', trigger: '3' },
         {value:"Data Science", label: 'Data Science', trigger: '4' },
         {value:"AI & Deep Learning", label: 'AI & Deep Learning', trigger: '4' },
       ],
     },
     {
       id: '3',
       message: 'Wrong answer, try again.',
   
     },
     { 
       id: '4',
       message: 'Awesome! You are a telepath!',
   
     },
    ];

![Bd32IFGAY9](https://user-images.githubusercontent.com/46730171/208125360-f97ceba1-cae8-4640-b78f-129dff9c5ef1.png)

**Comment by tatianafrank** [comment]
I just installed the library and having the same issue.

**Comment by IbrahimLakhzine** [comment]
For the rendering on index.js you can remove the strict mode for rendering and use a normal rendering worked for me.

**Comment by tatianafrank** [comment]
thanks that worked

**Comment by IbrahimLakhzine** [comment]
You are welcome.
