### ISSUE TITLE
Trigger not working

### ISSUE THREAD

**Issue by avnkailash** [LucasBassetti/react-simple-chatbot#37]
I am trying to implement my own Chat bot. I am totally stuck in the first example "Previous Values". The option Trigger is not working for me. Please help me in understanding where I am going wrong.

Below is the code.

```
import React from 'react';
import ReactDOM from 'react-dom';
import ChatBot from 'react-simple-chatbot';


const steps = [
    {
      id: '1',
      message: 'What is your name?',
      trigger: '2',
    },
    {
      id: '2',
      user: true,
      trigger: '3',
    },
    {
      id: '3',
      message: 'Hi {previousValue}, nice to meet you!',
      end: true,
    },
  ];



ReactDOM.render(
  <div>
    <ChatBot steps={steps} />
  </div>,
  document.getElementById('root')
);

```

**Comment by LucasBassetti** [comment]
Hi,

Is there some console error that you can provide?

**Comment by avnkailash** [comment]
Below is the exception I am seeing in the concole.

```
Uncaught TypeError: this.updater.enqueueCallback is not a function
    at t.r.setState (react-simple-chatbot.js:1)
    at react-simple-chatbot.js:1
```

**Comment by LucasBassetti** [comment]
Please check #34

**Comment by avnkailash** [comment]
Awesome. I got it working after downgrading my react and react-dom modules.

**Comment by Dkumarsable** [comment]
Please help me what is that ?
TypeError: Cannot read property 'length' of undefined
t.value
node_modules/react-simple-chatbot/dist/react-simple-chatbot.js:1
