### ISSUE TITLE
how to change the bot avatar ?

### ISSUE THREAD

**Issue by valdesguefa** [LucasBassetti/react-simple-chatbot#376]
I set the botAvatar props to the name of the image in the same directory as my javascript file
bellow the bot avatar didn't show
![image](https://github.com/LucasBassetti/react-simple-chatbot/assets/74729453/192a1df1-b9ea-4066-8a69-dfde2582ec81)

 <Layout  >
            <Component {...props} />
            <Wrapper>
              <ThemeProvider theme={theme}>
                <ChatBot

                  headerTitle="Speech Synthesis"
                  speechSynthesis={{ enable: true, lang: 'en' }}
                  steps={steps}
                  botAvatar="robot_AI.png"
                  floating recognitionEnable
                />
              </ThemeProvider>
            </Wrapper>
          </Layout>

**Comment by valdesguefa** [comment]
` <Layout  >
            <Component {...props} />
            <Wrapper>
              <ThemeProvider theme={theme}>
                <ChatBot

                  headerTitle="Speech Synthesis"
                  speechSynthesis={{ enable: true, lang: 'en' }}
                  steps={steps}
                  botAvatar="robot_AI.png"
                  floating recognitionEnable
                />
              </ThemeProvider>
            </Wrapper>
          </Layout>`

**Comment by pascalgagneur** [comment]
I don't how your project is set up. But if it create react app or similar you could just import your image.
`
import botAvatarImg from '[path-to-asset]/robot_AI.png
...
botAvatar={botAvatarImg}
`

**Comment by valdesguefa** [comment]
Thanks it work
