### ISSUE TITLE
Custom component doesn't re-render an update state

### ISSUE THREAD

**Issue by mehd-io** [LucasBassetti/react-simple-chatbot#38]
First : great work !
I'm having hard time to update a props in a custom component and I finally though it's because I see it as a child component but it's not ?
I've already ask the question here as I think that it was more a React mistake : 
https://stackoverflow.com/questions/46543778/react-child-props-doesnt-update-when-parent-state-change
Hope you could clarify this :-)

**Comment by LucasBassetti** [comment]
Hi, thanks!

Can you provide more details of your custom components and what props are you trying to update?

**Comment by mehd-io** [comment]
As stated just in the above link,
here is my custom component, I want to update sessionId props as it takes some time to receive it when I open the socket (connection props is working good) :
>
    import React, { Component } from 'react';
    import PropTypes from 'prop-types';
    import ChatBot from 'react-simple-chatbot';

    export class ProcessMessage extends Component {
      constructor(props) {
         super(props);

         this.state = {
           messages: [],
         };
       }

      componentWillMount() {
        const input = {
          type: 'user',
          sessionId: this.props.sessionId,
          msg: 'test message send to socket!',
        };
        //send message to websocket
        this.props.connection.send(input)

        this.props.connection.onmessage = evt => {
          // add the new message to state
          const msg = JSON.parse(evt.data);

          let responseText = msg.msg;
          this.setState({
            messages : responseText
          })
        };



      }


      render() {
        return <div>{ this.state.messages}</div>;
      }
    }
`
and the parent component :
>
    import React, { Component } from 'react';
    import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
    import PropTypes from 'prop-types';
    import { ThemeProvider } from 'styled-components';
    import ChatBot from 'react-simple-chatbot';
    import { ProcessMessage } from './components/processMessage.js';

    export class App extends React.Component {
      constructor(props) {
        super(props);
        // Assign state itself, and a default value for items


      }
        componentWillMount() {
            const theme = {
              background:      '#f5f8fb',
              fontFamily:      'Roboto, sans-serif',
              headerBgColor:   '#293846',
              headerFontColor: '#fff',
              botBubbleColor:  '#1AB394',
              userBubbleColor: '#fff',
              userFontColor:   '#293846',
              botFontColor:    '#fff',
            };

            const ChatBotTheme = {
              headerTitle:      'Recherchez un bien',
              bubbleStyle:      { overflow: 'visible', fontSize: '18px' },
              customStyle:      { background: '#fff', fontSize: '18px', overflow: 'visible' }, // 'ff4485', ff6070 How to change option background?
              // avatarStyle: {},
              // contentStyle: { overflow: 'visible', fontSize: '18px' },
              // inputStyle: {},
              style:            { overflow: 'visible', fontSize: '18px' },
              userDelay:        300,
              hideSubmitButton: true,
              floating: true,
            };
            const url = 'ws://localhost:4040';


            // this open websocket service
            this.connection = new WebSocket(url);

            this.setState(
              { theme: theme , ChatBotTheme: ChatBotTheme, connection:this.connection }
            );
            var sessionId;
            // listen to onmessage event
            this.connection.onmessage = evt => {

            // add the new message to state
              const msg = JSON.parse(evt.data);
                if (msg.type = "sessionId") {
                  sessionId=msg.msg;
                  console.log("now received sessionId " +sessionId);
                  this.setState(
                    { sessionId: sessionId}
                  );

                }
            };
      }

      render(){

        return (
          <MuiThemeProvider>
            <ThemeProvider theme={this.state.theme}>
              <ChatBot
                {...this.state.ChatBotTheme}
                steps={[
                  {
                  id: '1',
                  message: 'Hi, what's up?',
                  trigger: 'input',
                  },
                  {
                  id: 'input',
                  user: true,
                  trigger: 'result',
                  },
                  {
                    id: 'result',
                    component: <ProcessMessage sessionId={this.state.sessionId} connection={this.state.connection}/>,
                    asMessage: true,
                    trigger:'input',
                  },

                ]}
              />
            </ThemeProvider>
          </MuiThemeProvider>
        );

      }

    }
    App.propTypes = {
      children: PropTypes.element,
      sessionId: PropTypes.array.isRequired
    };
>
I also tried to put the const ChatbotTheme, theme, connection in the constructor w/ this.state and put the sessionId process in a componentDidMount. It did updates the state, but not the props in the custom component.

**Comment by LucasBassetti** [comment]
Hi. Try to use [componentWillReceiveProps](https://reactjs.org/docs/react-component.html#componentwillreceiveprops) in `ProcessMessage`

**Comment by mehd-io** [comment]
I did try something like below, but still no success :
>  
    import React, { Component } from 'react';
    import PropTypes from 'prop-types';
    import ChatBot from 'react-simple-chatbot';
    import axios from 'axios';
    import _ from 'lodash';
    import isEqual from 'lodash/isEqual';


    // This components take last user inputs with current session Id and send message to the backend api websocket
    // and render it
    export class ProcessMessage extends Component {
     constructor(props) {
        super(props);

        this.state = {
          messages: [],
          sessionId: props.sessionId,
        };
      }
      componentWillReceiveProps(newProps)
      {
        if (!isEqual(newProps.sessionId, "empty")) {
          console.log("update props!")
          this.setState({
            sessionId: newProps.sessionId,
          });
        }
      }

     componentDidMount() {
       const input = {
         type: 'user',
         sessionId: this.state.sessionId,
         msg: 'having a test!',
         tz: 'Europe/Brussels'componentWillReceiveprops
       };
       this.props.connection.onmessage = evt => {
         // add the new message to state
         const msg = JSON.parse(evt.data);

         let responseText = msg.msg;
         this.setState({
           messages : responseText
         })
       };

       console.log("in component sessionId "+this.state.sessionId);
       console.log("in component connection"+this.props.connection);

       this.props.connection.send(input)


     }


     render() {
       return <div>{ this.state.messages}</div>;
     }`

**Comment by LucasBassetti** [comment]
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import ChatBot from 'react-simple-chatbot';
import axios from 'axios';
import _ from 'lodash';

export class ProcessMessage extends Component {
  constructor(props) {
    super(props);

    this.state = {
      messages: [],
      sessionId: props.sessionId,
    };
  }
  
  componentWillReceiveProps(newProps) {
    const { sessionId } = nextProps;

    if (!sessionId) {
      this.setState({ sessionId });

      const input = {
        sessionId,
        type: 'user',
        msg: 'having a test!',
        tz: 'Europe/Brussels'componentWillReceiveprops
      };

      this.props.connection.onmessage = evt => {
        // add the new message to state
        const msg = JSON.parse(evt.data);
        const messages = msg.msg;

        this.setState({ messages });
      };

      console.log('in component sessionId ' + sessionId);
      console.log('in component connection ' + connection);

      this.props.connection.send(input)
    }
  }

  render() {
    return <div>{ this.state.messages}</div>;
  }
}
```

**Comment by mehd-io** [comment]
Hi @LucasBassetti , still not working BUT I've tried something which tells me that the problem may be in the implementation of the Chatbot component ? When I put the same component outside the chatbot component, it's working.
`    render(){

      return (
        <div>
        <ProcessMessage sessionId={this.state.sessionId} connection={this.state.connection}/> // the props of this component are updated
        <MuiThemeProvider>
          <ThemeProvider theme={this.state.theme}>
            <ChatBot
              {...this.state.ChatBotTheme}
              steps={[
                {
                id: '1',
                message: 'Hi, what's up?',
                trigger: 'input',
                },
                {
                id: 'input',
                user: true,
                trigger: 'result',
                },
                {
                  id: 'result',
                  component: <ProcessMessage sessionId={this.state.sessionId} connection={this.state.connection}/>, // the props of this component are not updated
                  asMessage: true,
                  trigger:'input',
                },

              ]}
            />
          </ThemeProvider>
        </MuiThemeProvider>
        </div>

      );

    }`

**Comment by LucasBassetti** [comment]
Hi. Maybe a solution can be create another component and set the state on it. Like that:

` component: <AnotherComponent /> `

```
class AnotherComponent extends Component {
  constructor() {
     super();
     this.state = { sessionId: undefined }
  }

      componentWillMount() {
        const theme = {
          background:      '#f5f8fb',
          fontFamily:      'Roboto, sans-serif',
          headerBgColor:   '#293846',
          headerFontColor: '#fff',
          botBubbleColor:  '#1AB394',
          userBubbleColor: '#fff',
          userFontColor:   '#293846',
          botFontColor:    '#fff',
        };

        const ChatBotTheme = {
          headerTitle:      'Recherchez un bien',
          bubbleStyle:      { overflow: 'visible', fontSize: '18px' },
          customStyle:      { background: '#fff', fontSize: '18px', overflow: 'visible' }, // 'ff4485', ff6070 How to change option background?
          // avatarStyle: {},
          // contentStyle: { overflow: 'visible', fontSize: '18px' },
          // inputStyle: {},
          style:            { overflow: 'visible', fontSize: '18px' },
          userDelay:        300,
          hideSubmitButton: true,
          floating: true,
        };
        const url = 'ws://localhost:4040';


        // this open websocket service
        this.connection = new WebSocket(url);

        this.setState(
          { theme: theme , ChatBotTheme: ChatBotTheme, connection:this.connection }
        );
        var sessionId;
        // listen to onmessage event
        this.connection.onmessage = evt => {

        // add the new message to state
          const msg = JSON.parse(evt.data);
            if (msg.type = "sessionId") {
              sessionId=msg.msg;
              console.log("now received sessionId " +sessionId);
              this.setState(
                { sessionId: sessionId}
              );

            }
        };
  }

  render() {
    return <ProcessMessage sessionId={this.state.sessionId} connection={this.state.connection}/>
  }
}

**Comment by LucasBassetti** [comment]
Is worked?

**Comment by mehd-io** [comment]
Hi @LucasBassetti , thx for the suggestion, I end up by the same idea actually but still weird why inside the chatbot component, it wasn't updated.
