### ISSUE TITLE
How can i access the css classes so i can change the styling of the chatbot?

### ISSUE THREAD

**Issue by kh272** [LucasBassetti/react-simple-chatbot#40]

**Comment by LucasBassetti** [comment]
Hi!

You can use the style props (bubbleStyle, contentStyle, customStyle, ...) to override the current styles. Please check the API reference [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot).

You can also use defining a new theme. Check how to do that [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/themes)

**Comment by kh272** [comment]
Hey, yeah i have checked those already but those theme props are a bit limited, are there any more props? Like changing the height and the width of the conversation, changing the styling of the title etc..

**Comment by LucasBassetti** [comment]
Yes, you can use this style props [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot).

Example:
```
<ChatBot
  steps={steps}
  bubbleStyle={{ fontSize: '10px' }}
/>
```

**Comment by ejuarez1293** [comment]
How can I set up the size of the floating icon and possible change the message bubble into even the avatar icon?

**Comment by sbadiger708** [comment]
Hey.
After building the code chatbot is not looking good. can you please help me out with this.
<img width="1440" alt="Screenshot 2020-01-31 at 5 20 25 PM" src="https://user-images.githubusercontent.com/38648256/73630351-cba91900-467b-11ea-9064-59a88c2af901.png">

**Comment by sjain3097** [comment]
how to change headline of the chatbot

**Comment by pascalgagneur** [comment]
`<ChatBot steps={steps} headerTitle="Hello World" />`

**Comment by HamzaTahir12345** [comment]
can we change the floating icon in chatbot?

**Comment by Prahladkumar11** [comment]
can we change height and weight of the chatbot container

**Comment by BenedictCodeQuick** [comment]
Is there a way to apply custom styles to a particular option? Appreciate your answers!
