### ISSUE TITLE
Is there a way to save the conversations with chatbot for future use?

### ISSUE THREAD

**Issue by kh272** [LucasBassetti/react-simple-chatbot#41]

**Comment by LucasBassetti** [comment]
You can `cache={true}` to keep the current conversation in cache

**Comment by kh272** [comment]
I did that but then i got an error saying "localStorage not defined"

**Comment by LucasBassetti** [comment]
What browser are you using and what version?

**Comment by kh272** [comment]
Google Chrome. Not sure about the version because i don't have access to that computer at the moment

**Comment by kh272** [comment]
Google Chrome Version 57.0.2987.133 (64-bit)

**Comment by LucasBassetti** [comment]
Can you try update chrome and check if works?
