### ISSUE TITLE
Styled-Components throws console error 

### ISSUE THREAD

**Issue by chapmanc** [LucasBassetti/react-simple-chatbot#46]
When loading the library with a fresh npm install I get the following.

`ThemeProvider.js:63 Warning: Usage of `context.__styled-components__` as a function is deprecated. It will be replaced with the object on `.context.__styled-components__next__` in a future version.

Fixed this by explicitly downgrading my peer dependency from ^2.2.1 to ^2.1.2 for the time being.

**Comment by LucasBassetti** [comment]
Hi, sorry for delay. I used the last version of styled-components `v2.2.3` and works fine apparently. I will close this issue but feel free to open if you find a problem.

Thank you!

**Comment by malithmcr** [comment]
I faced the same problem.
I have to install styled component if I want to use react-simple-chatbot. Is there any way you could include this already in npm package?
