### ISSUE TITLE
Passing a function into options

### ISSUE THREAD

**Issue by yubofredwang** [LucasBassetti/react-simple-chatbot#47]
Hi, what I am trying to do is to connect the options to a React props thus I can change the value and label of the options every time I update the props. for the message I could be doing 

message: () => {
                      return  this.props.text;
}

However, 
options: this.props.options will only take in the options at initial state
and 
options: () => {
                      return  this.props.options;
}
will result in a error basically saying that options can only be a object

**Comment by LucasBassetti** [comment]
Hi,

Options can't be a function. You should use array instead. Like that:

```
options: [
    { value: 1, label: 'Number 1', trigger: '3' },
    { value: 2, label: 'Number 2', trigger: '2' },
    { value: 3, label: 'Number 3', trigger: '2' },
  ]
```

**Comment by yubofredwang** [comment]
But what if I want to dynamically use the option, say I want to get the options from the server.

**Comment by LucasBassetti** [comment]
So, in this case I recommend you create your own custom option component using the `custom step` with `waitAction: true`. You can use it to load the content from server and use the `triggerNextStep` function to trigger the next step when user select a option.

**Comment by GilbertMizrahi** [comment]
Any example of how to use the triggerNextStep?
I haven't figured it out how to use it.

**Comment by rajivgandhi2010** [comment]
> So, in this case I recommend you create your own custom option component using the `custom step` with `waitAction: true`. You can use it to load the content from server and use the `triggerNextStep` function to trigger the next step when user select a option.

We can able to send the message from custom component. Is there any way to send Options from custom component to steps?

**Comment by yubofredwang** [comment]
> > So, in this case I recommend you create your own custom option component using the `custom step` with `waitAction: true`. You can use it to load the content from server and use the `triggerNextStep` function to trigger the next step when user select a option.
> 
> We can able to send the message from custom component. Is there any way to send Options from custom component to steps?

When I was doing my project, I was not able to figure out a way to change the options effectively. However, I simply used a combination of Table Content and the Options

A | Option A
B | Option B
C | Option C

Then you prompt user to select A or B or C as common usage, you can write some react logic that links the content with the option. Though this is only the alternative solution, it may save you a lot of time trying to modify the code with JQuery.

Hope this helps!

**Comment by rajivgandhi2010** [comment]
> > > So, in this case I recommend you create your own custom option component using the `custom step` with `waitAction: true`. You can use it to load the content from server and use the `triggerNextStep` function to trigger the next step when user select a option.
> > 
> > 
> > We can able to send the message from custom component. Is there any way to send Options from custom component to steps?
> 
> When I was doing my project, I was not able to figure out a way to change the options effectively. However, I simply used a combination of Table Content and the Options
> 
> A | Option A
> B | Option B
> C | Option C
> 
> Then you prompt user to select A or B or C as common usage, you can write some react logic that links the content with the option. Though this is only the alternative solution, it may save you a lot of time trying to modify the code with JQuery.
> 
> Hope this helps!

Can you please share me the sample for the above?
