### ISSUE TITLE
Input field disabled

### ISSUE THREAD

**Issue by grinono** [LucasBassetti/react-simple-chatbot#48]
in the examples of https://lucasbassetti.com.br/react-simple-chatbot/#/docs/hello-world
The typing field is disabled. Same a my local version.

HTML shows: value disabled
Why? and how to change this to enable

**Comment by grinono** [comment]
componentDidMount () {
    document.getElementsByClassName('rsc-input')[0].disabled = false
  }

**Comment by LucasBassetti** [comment]
Hi, the input is just enable when you have a user step. Otherwise it will be disabled.

Check an example [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/previous-value)

**Comment by githubuserVivek** [comment]
Hi Lucas

I want to hide the input field and change the height of the chatbot, how can I do that?
