### ISSUE TITLE
Examples do not progress past step 1

### ISSUE THREAD

**Issue by bfarrgaynor** [LucasBassetti/react-simple-chatbot#50]
I seem to have this strange issue where the examples do not go past the first step.

https://www.dropbox.com/s/c32ti5iare4ipfe/Screenshot%202017-10-30%2011.33.25.png?dl=0

```
class AppSSChat extends Component {

 render() {
     
     return (
          
            <ChatBot
            
              steps={[
                {
                  id: "1",
                  message: "What number I am thinking?",
                  trigger: "2"
                },
                {
                  id: "2",
                  options: [
                    { value: 1, label: "Number 1", trigger: "4" },
                    { value: 2, label: "Number 2", trigger: "3" },
                    { value: 3, label: "Number 3", trigger: "3" }
                  ]
                },
                {
                  id: "3",
                  message: "Wrong answer, try again.",
                  trigger: "2"
                },
                {
                  id: "4",
                  message: "Awesome! You are a telepath!",
                  end: true
                }
              ]}
            />
        
          );
  }
}

export default AppSSChat;

```

I am loading this via a router, (react-router-dom). 

There are no errors in the console or anything??

```
├─ react-dom@16.0.0
└─ react@16.0.0
```

**Comment by LucasBassetti** [comment]
No console error? What version of the chatbot you are using?

**Comment by nicolas-wsk** [comment]
I probably had the same issue using [Gatsby](https://github.com/gatsbyjs/gatsby) and the last version of react-simple-chatbot (v0.2.8-beta.3).

I don't know if it's related but I had in the terminal:
```
npm WARN react-simple-chatbot@0.2.8-beta.3 requires a peer of react@^16.x but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-chatbot@0.2.8-beta.3 requires a peer of react-dom@^16.x but none is installed. You must install peer dependencies yourself.
```

I downgraded to 0.2.7 and everything is working fine!

**Comment by LucasBassetti** [comment]
@nicolas-wsk it means that you need instal react and react-dom 16 packages 

Example: `npm install react@16.0.0 react-dom@16.0.0`

**Comment by elliotaplant** [comment]
If you want to use Gatsby and `react-simple-chatbot` together, you can use the [gatsby-plugin-react-next
](https://www.npmjs.com/package/gatsby-plugin-react-next) to make Gatsby use react v16.
