### ISSUE TITLE
Behaviour of custom components that receive user inp

### ISSUE THREAD

**Issue by bibinbalakrishnan** [LucasBassetti/react-simple-chatbot#51]
First of all, great work on this wonderful library. I’m using custom component to receive user input ( date using date widget, file upload etc.). In all these cases after receiving the input it would be really awesome if there was some capability to render them as user bubble (so that it feels more natural). I would remove the rendering of my custom component after receiving the correct input and can render a user input bubble or some how pipe that information through the props.

**Comment by LucasBassetti** [comment]
Hi, thanks!

Unfortunately is not possible render as user bubble but you can render as bot bubble using the `asMessage: true` props in custom step.

But this is a good idea and maybe I can add this in next release.

Thank you!

**Comment by savanchhayani** [comment]
Hi, 
I want to implement functionality as custom component as user bubble,
Please give an example.
Thanks :)
