### ISSUE TITLE
What about Google Analytics?

### ISSUE THREAD

**Issue by dejandomarcas** [LucasBassetti/react-simple-chatbot#54]
Hi there,

first of all, thanks for the project, it's really nice and easy to use. I'm playing around with the posibility of integrate it on an ecommerce and could be very nice in order to find out products and services. As marketer guy, I would like to analyse and track the use of the chat. Is there any way to send data to Google Analytics of user behaviour? (any kind of hit -event, pageview, etc-)

Thank you!

**Comment by LucasBassetti** [comment]
Hi, thank you!

Unfortunately this is not possible yet. 

Maybe you can create a custom component with `replace: true` prop just to send information for google analytics. You will need create a step id hashmap to send the next step via this custom component.

But I'm not sure if this will work.
