### ISSUE TITLE
Add speech recognition option on supported browsers

### ISSUE THREAD

**Issue by puemos** [LucasBassetti/react-simple-chatbot#55]
Hey @LucasBassetti,

Awesome project !! :1st_place_medal: 

I wrote an improvement and a would like to add a PR but before let's talk about it.
It's working pretty good and I also **already wrote all the tests** :muscle: 

[react-simple-chatbot/tree/speech-recognition](https://github.com/puemos/react-simple-chatbot/tree/speech-recognition)

So on supported browsers, we can add speech recognition to replace the text (by adding a prop).

I'll be really happy if you can take a look
Thanks!

**Comment by LucasBassetti** [comment]
Hi @puemos,

Amazing PR! I will take a look ASAP. 

Thank you for your contribution! 👍
