### ISSUE TITLE
Confused about Toggle documentation and functionality

### ISSUE THREAD

**Issue by jeanmaried** [LucasBassetti/react-simple-chatbot#57]
Hi Lucas,

First off, thanks a ton for this amazing simple bot!

Here is my problem I have been stuck on for a bit. I am having trouble understanding the documentation for the toggle functionality. I am looking to replicate the exact same functionality you have on the bot website. Which is, when clicking a link inside the chat (like the one you have to redirect to the installation page), I am redirected to the appropriate page, then the chat closes.

I understand I need to use the opened prop along with the toggleFloating prop and then my own function. But I don't understand what the documentation means by: "Must be used with opened prop. You must use it to change your opened prop using your custom function like myToggleFloating({ opened })".

I was hoping you could give me an example of how you did it.

Here is my code simplified without all my failed attempts at adding these props:

```
import React, {Component} from 'react';
import {Link, withRouter} from 'react-router-dom';
import './styles.css';
import ChatBot from 'react-simple-chatbot';

class mrChatBot extends Component{
    handleAbout = ()=>{
        this.props.history.push('/about');
        return "3"
    }

    render(){
        return(
        <ChatBot floating={true} placeholder="Type your message..."
                steps={[
                        {
                            id: '1',
                            message: 'What can I help you with?',
                            trigger: '2',
                        },
                        {
                        id: '2',
                            options: [
                                { value: 1, label: "About", trigger: this.handleAbout, },
                            ],
                        },
                        {
                            id: '3',
                            message: 'You have been redirected!',
                            end: true,
                        },
                ]}
            />
        )
    }
}
        
export default withRouter(mrChatBot);
```

Thank you!

**Comment by LucasBassetti** [comment]
Hi,

You can check an example [here](https://github.com/LucasBassetti/react-simple-chatbot/blob/gh-pages/app/components/docs/Tutorial.jsx)

**Comment by jeanmaried** [comment]
Thank you! That allowed me to get it working!
