### ISSUE TITLE
Compatibility with React Native

### ISSUE THREAD

**Issue by Shauneoo** [LucasBassetti/react-simple-chatbot#6]
Hi @LucasBassetti, is there any plans to expand this to React Native?

**Comment by LucasBassetti** [comment]
Hi,

I thought about but I don't have any plans to expand yet. 

Maybe with a good adoption I can expand it. 😄

**Comment by LucasBassetti** [comment]
Hi @Shauneoo,

There is a initial experiment that you can check [here](https://github.com/LucasBassetti/react-native-chatbot)
