### ISSUE TITLE
notification sound

### ISSUE THREAD

**Issue by chiragmewada** [LucasBassetti/react-simple-chatbot#61]
Hi,

Thanks for writing beautiful open source component.

I would like to play sound with bot reply/notification. Can you help me, how can I achieve this?

**Comment by LucasBassetti** [comment]
Hi, thank you!

Unfortunately the chatbot doesn't have support to notification yet.

**Comment by chiragmewada** [comment]
Thanks for the quick reply.
Is there a way, I can play a sound when bubble event occur?
