### ISSUE TITLE
How to validate user input with async function?

### ISSUE THREAD

**Issue by marcoizzo** [LucasBassetti/react-simple-chatbot#62]
I have to validate a user email with my backend using a fetch call. Can I do this? I'm trying with async/await but does not work.

My code:

```
function resolveClientEmailAddress(email) {
   return new Promise(resolve => {
     let data = new FormData();
    data.append( "client", email);
    fetch(config.server.remote + "api/client-by-mail/", {
               method: "POST",
               body: data
            }).then(function(res){ return res.json(); }).then(function(data){
               resolve(data)
            }).catch(function (error) {
               console.log("CATCH ----> ERROR ===> ", error)
             });
         });
      }

      async function clientEmailValidator(email) {
         let response = await resolveClientEmailAddress(email);

         console.log("clientEmailValidator ===> ", response); // 10

         if (response.hasOwnProperty('error_message'))
            return response.error_message;
         else
            return true
      }

      let chatbotQuestionList = [{
         id: '1',
         message: 'Welcome',
         trigger: '2',
      },{
         id: '2',
         message: "Insert your email address",
         trigger: '3',
      },{
         id: '3',
         user: true,
         validator: clientEmailValidator,
         trigger: 'end',
      },{
         id: 'end',
         message: 'Ok',
         end: true,
      }];

```

**Comment by LucasBassetti** [comment]
Hi @marcoizzo,

Unfortunately we can't do async validator in this way yet (but it's a good ideia for next release). 

As you can do now is create a custom component with `waitAction: true` to validade the email. If it's incorrect you trigger the step 3 again. If it's correct you trigger the `end` step.

**Comment by Thomas-Negrault** [comment]
@LucasBassetti Can you provide an example of the use of `waitAction: true` in this particular case ? I would like to do something similar, sending the user input into my backend, and depending on the response, trigger the next step.

I made it work with a synchronous Ajax request but it is deprecated, I think the custom component solution is the correct way to do it but even with the wikipedia example, I do not know how to do it

**Comment by LucasBassetti** [comment]
Hi @Thomas-Negrault,

You can check a similar example [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)

After the user type his desire search, I use the value to make a async call in dbpedia. After get the answer I show the user a button to search again.

You can make a custom component to get the user input and make your validation. After that you can trigger some step automatically using the [triggerNextStep](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component) prop

**Comment by Thomas-Negrault** [comment]
But how to trigger the next step without displaying anything ?
Using the wikipedia example I can trigger the next step with the return of my Ajax call but I have a white box with the loading dots, and then an empty white box (as the render of my component is empty):
![image](https://user-images.githubusercontent.com/6841201/34778997-3e490e20-f61f-11e7-8674-9427e6f6036a.png)

Is it possible to not displaying this div ? The ideal user experience would be the bot writing indicator:
![image](https://user-images.githubusercontent.com/6841201/34778939-0fb09902-f61f-11e7-901c-272a0a095696.png)

**Comment by LucasBassetti** [comment]
Please try to add the `asMessage: true` and `replace: true` props in the [custom step](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps). Not sure if will work as you want.

**Comment by Thomas-Negrault** [comment]
Yes that's pretty much what I want ! With theses two props and this render for my component:
```
return Loading()
```
The behaviour is:

1. The user enter its input
2. The bot display the "loading/writings" dots as the ajax call is made
3. When the ajax call is finish, the bubble of my component disapear and another one with the conditional step appears.

Is there a nicer way to display the loading dots ? Maybe you have a React component that I could use.

**Comment by Balthazar33** [comment]
> Yes that's pretty much what I want ! With theses two props and this render for my component:
> 
> ```
> return <Loading/>
> ```
> 
> The behaviour is:
> 
> 1. The user enter its input
> 2. The bot display the "loading/writings" dots as the ajax call is made
> 3. When the ajax call is finish, the bubble of my component disapear and another one with the conditional step appears.
> 
> It is just a little bit weird that the bubble disappears and then reappears with the dots.. can we set the botDelay to 0 for a single step ?
> 
> Edit: found it: the `delay` option on the step, sorry !
> 
> The render is amazing ! Thank you !

Hi @Thomas-Negrault 
Can you please provide a snippet of your implementation?

I wanted to call the next step conditionally (for eg., step with id '5' for a successful API call and step '6' for a failed one.)

Thanks!
