### ISSUE TITLE
Custom component with asMessage doesn't receive previousStep

### ISSUE THREAD

**Issue by thirdhand** [LucasBassetti/react-simple-chatbot#64]
When I render a custom component in a step with `asMessage: true` the component receives an empty object instead of the previous step. It looks like [the `TextStep` component isn't provided the `previousStep` prop in the `renderStep` method](https://github.com/LucasBassetti/react-simple-chatbot/blob/6684dac35467d1847453ed56bb129a2ae3392c56/lib/ChatBot.jsx#L460).

**Comment by LucasBassetti** [comment]
I will change it asap. Thank you for reporting!
