### ISSUE TITLE
Usage of `context.__styled-components__` as a function is deprecated

### ISSUE THREAD

**Issue by azimitina** [LucasBassetti/react-simple-chatbot#66]
Hey
I am using v0.2.6
The latest version does not work with my project (as I am using React 15
I followed the example of theming in the website
https://lucasbassetti.com.br/react-simple-chatbot/#/docs/themes

Can you please let me know what I need to change ?
```
Warning: Usage of `context.__styled-components__` as a function is deprecated. It will be replaced with the object on `.context.__styled-components__next__` in a future version.
```

**Comment by LucasBassetti** [comment]
What version os styled components are you using?

**Comment by azimitina** [comment]
"styled-components": "^2.4.0"

**Comment by LucasBassetti** [comment]
This is prabably a problem with the version `2.4.0` of styled components. Try to install an old one.
