### ISSUE TITLE
Responsive width

### ISSUE THREAD

**Issue by voluntadpear** [LucasBassetti/react-simple-chatbot#67]
Hi! first of all, thank you for this awesome project. 

I noticed that for small screens the width is fixed at 100%, and there's no way for me to change that because it's hard-coded. https://github.com/LucasBassetti/react-simple-chatbot/blob/22502202abb1700f9be7ec6bf4496ba1baf0cd2c/lib/ChatBotContainer.jsx#L24

I think it would be nice to be able to change this as a prop.

**Comment by engrtitus** [comment]
The chatbox class is .kdZMGe , you can adjust the width with css media queries

**Comment by LucasBassetti** [comment]
Hi @voluntadpear,

I recommend you keep 100% for small screens for a better user experience. But if you want to change you overlap the css using the prop `className` and the container class `.rsc-container`  

Example:

```
.${yourClassNameProp} {
  .rsc-container {
    // overlapping content
  }
}
```
