### ISSUE TITLE
Page jumps to react-simple-chatbot component

### ISSUE THREAD

**Issue by engrtitus** [LucasBassetti/react-simple-chatbot#68]
I am using React-simple-component in an existing React App. The Page keeps scrolling down to the chat section on page reload

**Comment by LucasBassetti** [comment]
Hi @engrtitus,

Can you provide more details (screenshots, your code, etc.)?

**Comment by engrtitus** [comment]
I am using it in an existing ReactJs App. This is how i am displaying the various components in my App.js. 

`         <Header></Header>
          <Questions></Questions>
          <Detection></Detection>
          <Funke></Funke>
          <Created></Created>
          <Footer></Footer>`

The Funke component is the chat component. The page scrolls down to Funke whenever i reload/open the page.

**Comment by engrtitus** [comment]
@LucasBassetti  I have discovered it was being caused by function(){e.input.focus()} . If i remove it, it does not scroll to the chat section but it removes the input focus ability. The user needs to keep clicking the input field to enter a value

**Comment by LucasBassetti** [comment]
You can create an option step to user start the chat and prevent this problem. Example:

```
{
  id: '1',
  options: [
    { value: 2, label: 'Start', trigger: '2' },
  ],
},
{
  id: '2',
  user: true,
  trigger: '3'
},
...
```

**Comment by engrtitus** [comment]
Thanks a lot. But my use case requires the user to answer a question to start the chat. I was able to make it work with CSS . I wrapped the the chatbot component in a div with className chatBot.

`.chatBot {
  -webkit-animation: chatIn 3s;
  animation: chatIn 3s;
}

@keyframes chatIn {
	0%, 50% { opacity: 0; visibility: hidden;}
	100% { opacity: 1; visibility: visible; }
}`
