### ISSUE TITLE
Proposal - Style user bubble differently to bot bubble

### ISSUE THREAD

**Issue by cjke** [LucasBassetti/react-simple-chatbot#69]
First: This is an awesome library.

Proposal 1:
So much apps, like iphone messages, Hangouts, etc, show users as different colors. This allows, at a glance, to see what bubbles appear to who. 

I suggest this library allows for something similar. 

Happy to PR

![image](https://user-images.githubusercontent.com/884065/35773340-34f1fe44-09a3-11e8-9296-dbc6dff0cc82.png)

Proposal 2:
Allow hover to be styled for options. At the moment, it defaults to opacity 0.7 without the ability to change.

**Comment by cjke** [comment]
@engrtitus That comes close, but it allows only the change of botBubbleColor and botFontColor as seen here: https://github.com/LucasBassetti/react-simple-chatbot/blob/afacd7f06e168bed9b408564ea9658d99781452b/lib/steps/options/OptionElement.jsx

The `bubbleStyle` also comes close, but doesn't allow us to apply that style differently for bot and the user.

I think theme is good for general purpose things - overarching colors, fonts, etc. 
The style props seem more suited to fully changing the bubble. 

I suggest an extra two props:
 - botBubbleStyle
 - userBubbleStyle

**Comment by LucasBassetti** [comment]
Hi,

I will consider put this props in a next release.

Thank you!

**Comment by cjke** [comment]
Curious if this was still on the road map? As mentioned, I could PR

**Comment by weimawt** [comment]
Where can I change the user and bot bubble style separately ?
