### ISSUE TITLE
Error - Invariant violation: View config not found for h2

### ISSUE THREAD

**Issue by hart-zhou** [LucasBassetti/react-simple-chatbot#70]
Try the sample form and other examples. on iOS it returns the error \

Invariant violation: View config not found for h2

**Comment by hart-zhou** [comment]
follow the example https://lucasbassetti.com.br/react-simple-chatbot/#/docs/form
Thank you for your help

**Comment by LucasBassetti** [comment]
Do this happens when you open the example in the iOS?

**Comment by hart-zhou** [comment]
yes, i see same error on iOS too.

**Comment by LucasBassetti** [comment]
Can you send a screenshot?
