### ISSUE TITLE
Great app so far just a few questions

### ISSUE THREAD

**Issue by btotharye** [LucasBassetti/react-simple-chatbot#71]
So I'm just learning react now coming from Angular and I'm setting up an escalation bot using this project.  My only question is once the conversation is done on the simpleform for example is there a way to just put in there to have it auto start over without refreshing the page or do you have any suggestions on this?

Also is there a easy way to have it on your existing html pages as a script component so you can have the chat button basically?

Thanks again and liking the project so far

**Comment by LucasBassetti** [comment]
Do you want refresh the chatbot after finish?

_**Also is there a easy way to have it on your existing html pages as a script component so you can have the chat button basically?**_

Are you talking about put a js script of the chatbot in the html page? If yes, maybe you can do some like that (not sure if works): [https://stackoverflow.com/a/14033306/5173959](https://stackoverflow.com/a/14033306/5173959)

**Comment by btotharye** [comment]
For now I just built into the last step it to re-trigger the opening step which works for now, as far as embedding the chatbot I meant more how you have it setup here https://lucasbassetti.com.br/react-simple-chatbot/#/docs/hello-world where you have the chat bubble on the bottom right.

**Comment by LucasBassetti** [comment]
You can check the website example [here](https://github.com/LucasBassetti/react-simple-chatbot/blob/gh-pages/app/components/docs/Tutorial.jsx)

Basically you just need create a state to do that. Example:

```
state = {
  reload: false,
}

reloadChatBot() {
 this.setState({ reload: true }, () => {
   this.setState({ reload: false });
 });
}

render() {
  if (this.state.reload) {
    return <span />
  }

  return (
    <ChatBot steps={steps} />
  )
}
```
