### ISSUE TITLE
External Calls Axios, etc

### ISSUE THREAD

**Issue by btotharye** [LucasBassetti/react-simple-chatbot#73]
Hey its me again lol but before I start setting up this next part of my bot I wanted to confirm with you the best approach here.  If I want to take in input and then make api calls with that would I use something like https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia or could I just create a React component with axios to do this work for me and somehow pass in the data from the bot to that component?

Wasn't sure the best approach on this, anything you can offer will be helpful I'm going to start building it out today and testing out a few things.

Thanks

**Comment by btotharye** [comment]
think I have a handle on this now thanks

**Comment by wcousin** [comment]
Can you share your code for integrating external API responses? I'm trying to figure this out too.
