### ISSUE TITLE
HTML/Hyperlinks in Message

### ISSUE THREAD

**Issue by btotharye** [LucasBassetti/react-simple-chatbot#75]
## Description
Is it possible to do html or hyperlinks in the message responses or would this have to be a custom component to do this?

Right now its just text url's not actually creating a hyperlink that can be clicked on from the chat.

Thanks

**Comment by btotharye** [comment]
Basically for now I've done it like the demo here https://btotharye.github.io/mycroft-chat/ and the code is at https://github.com/btotharye/mycroft-chat curious if this is the right way to do this or if there is a better way.

Thanks again really liking this package.

**Comment by LucasBassetti** [comment]
Hi @btotharye, 

You're doing right 👍 😄

**Comment by smasschelin** [comment]
Hello,

I know this issue has been closed for several months, but this something that I'm actively working on at the moment and I don't quite know what to do next. The links for the repos mentioned (for me) give a 404 error. I'm using RASA as my back-end for NLP work. Is this something that would need to be done within RSC (I think within Storage.js?), or is this something that RASA should handle?  If either of you still have this on your radar, I'd appreciate any assistance on this.

Thank you, and thanks for such a great module.
