### ISSUE TITLE
How to change the height and width of the chatbot component?

### ISSUE THREAD

**Issue by GilbertMizrahi** [LucasBassetti/react-simple-chatbot#76]
I have tried to do something similar to the example theming, but it doesn't seem to work.

I created a test project with create-react-app but when importing the theming example (as is or modified affecting content) into the App.js is complaints that the ThemedExample component is null.

I would appreciate some suggestions and/or examples.

**Comment by LucasBassetti** [comment]
You can use the style props [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot)

**Comment by GilbertMizrahi** [comment]
Thanks. That helped a lot, but I don't see how to change the height of the content area.

I guess for that I should use contentStyle, but I don't know what value to assign to change the height of the content area.

BTW, this is a great library. Thank you for doing it :)

**Comment by chandjenAC** [comment]
Hi, how to change the height of the content area ?

**Comment by chandjenAC** [comment]
Hi , I got it. 

Example : In case anyone is in need. Both contentStyle and style needs to be modified.

`contentStyle={{height:"600px"}}`
`style={{height:"710px"}}`

**Comment by XudongLiu** [comment]
Hi, only setting contentStyle is working for me.
my code is :
contentStyle={{height:(window.innerHeight-120) + 'px'}}
that works well.
