### ISSUE TITLE
How to reuse the option step component?

### ISSUE THREAD

**Issue by markslh** [LucasBassetti/react-simple-chatbot#77]
Thanks for your great effort. I'm using the ajax to communicate the bot with my server, and I want to pop the options according to the data received from the server. But I feel confused in using the OptionsStep component (basically I cannot make it work, and I noticed that you are using the Loading component in your wikipedia example).  Would you mind adding some documentation about these components or maybe some examples? Thanks a lot XD.

**Comment by LucasBassetti** [comment]
Hi @markslh, thank you! :)

You can check some examples [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/previous-value) and more details about the steps [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps).

If you want create a dynamic option component based in the data received from server I recommend you create your own option component using the [custom component](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component).

You can combine the `waitAction` prop to wait an user action and `triggerNextStep` to trigger the next step based in the user action.

**Comment by rajivgandhi2010** [comment]
> Hi @markslh, thank you! :)
> 
> You can check some examples [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/previous-value) and more details about the steps [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps).
> 
> If you want create a dynamic option component based in the data received from server I recommend you create your own option component using the [custom component](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component).
> 
> You can combine the `waitAction` prop to wait an user action and `triggerNextStep` to trigger the next step based in the user action.

I can able to create an option component. But the styling is different comparing with default options component in react bot.
