### ISSUE TITLE
cannot work with styled-component

### ISSUE THREAD

**Issue by source2git** [LucasBassetti/react-simple-chatbot#78]
## Description

i use create-react-app to build a empty workspace, only import **react-simple-chatbot** and **styled-components**, but seem like some of css fail to load, neither error nor warning in console, just render incorrectly.

## Screenshots

code: ![image](https://user-images.githubusercontent.com/13177782/37139631-82ccaed6-22a6-11e8-97db-f2924201a619.png)

page: 
![image](https://user-images.githubusercontent.com/13177782/37139675-a4c112d4-22a6-11e8-96fe-e916b966aecf.png)

![localhost_3000_](https://user-images.githubusercontent.com/13177782/37139742-e4629598-22a6-11e8-8426-2584d77ae121.png)

**Comment by LucasBassetti** [comment]
What version of react-simple-chatbot and styled-components are you using?

**Comment by source2git** [comment]
"react": "^16.2.0",
"react-dom": "^16.2.0",
"react-scripts": "1.1.1",
"react-simple-chatbot": "^0.2.9",
"styled-components": "^3.2.1"

**Comment by LucasBassetti** [comment]
Try delete the styled-components and reinstall the chatbot and tell me if works

**Comment by source2git** [comment]
sry for belated feedback
i try this：
`npm uninstall styled-components`
`npm install react-simple-chatbot`
still cannot work properly

**Comment by LucasBassetti** [comment]
Did you test open it in another browser?

**Comment by source2git** [comment]
yep, same issue. i will try this on my own pc this week

**Comment by elliotaplant** [comment]
I'm running into a similar issue using Gatsby - it appears that the robot SVG size is not limited before the chatbot mounts. I'll look into seeing if I can figure out why.

**Comment by uadp** [comment]
I have same issue like this, but i didn't know if it similar.

And i was break this issue.

I Solve this with react-dom, which loaded by webpack bundle.js. 
Be sure it rendered on client-side.

**Comment by LucasBassetti** [comment]
Hi @uadp,

Can you provide some code of your solution? Thank you!

**Comment by wcousin** [comment]
Are there any updates to this? I'm getting this error as well...
