### ISSUE TITLE
IBM WATSON

### ISSUE THREAD

**Issue by rogeriorioli** [LucasBassetti/react-simple-chatbot#79]
## Description

hi , i have application returns a json from api RESTFULL , i need integrated this on your component . 

What exemple is more usually ? simple-form ? validator ? 
is possible consume restfull APIS ?

**Comment by LucasBassetti** [comment]
Please check #32

**Comment by rogeriorioli** [comment]
Thanx Lucas , works fine !

**Comment by leslyarun** [comment]
@rogeriorioli Can u please provide me a real-world example, where u used custom steps?
