### ISSUE TITLE
Is there a way to save the last step, so if user returns the app will now where the user left?

### ISSUE THREAD

**Issue by GilbertMizrahi** [LucasBassetti/react-simple-chatbot#80]
I know that if I use cache={true} when the user returns it will continue from where it left.

However, I want to have a step that asks something such as:
"Hey! Nice to see you here again. Would you like to continue the conversation or start over?"
and provide options:
"Start Again" and "Continue"

Is that possible? if so, how?

**Comment by LucasBassetti** [comment]
Unfortunately is not possible yet

**Comment by GilbertMizrahi** [comment]
Is it possible to know what is the last step, when people leave?
