### ISSUE TITLE
Question - Set value of step from within custom component

### ISSUE THREAD

**Issue by Shauneoo** [LucasBassetti/react-simple-chatbot#82]
## Description
Hi, as the title states. Can you set the value of the step from within a custom component. I.e. get image path from camera (in first step) then display this in a subsequent step.

## Screenshots
<img width="280" alt="screen shot 2018-03-27 at 16 10 50" src="https://user-images.githubusercontent.com/5374745/37976441-7144434e-31d9-11e8-85da-0e11a737a688.png">

**Comment by LucasBassetti** [comment]
Yes, you can set the value using the [triggerNextStep({ value, trigger })](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component)

**Comment by GeoFro** [comment]
How do access the value from within another step?
For example, I'd like to grab the `value` and put it into the `message: ` of another step but I don't know the syntax.
