### ISSUE TITLE
delay the appearance of the gif loader...

### ISSUE THREAD

**Issue by fguespe** [LucasBassetti/react-simple-chatbot#85]
its weird that it starts loading right after user input, i use botdelay but as i say, dont look nice.

botdelay should delay the bubble loader i think..., no the text

**Comment by LucasBassetti** [comment]
The `botDelay` is a delay to simulate bot typing. It come before the text. You can also put a delay for each step. Check the delay attribute [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps)
