### ISSUE TITLE
Custom Component results to Review

### ISSUE THREAD

**Issue by DianaCristina** [LucasBassetti/react-simple-chatbot#87]
## Description
 I have an issue. I have a custom component: MultiSelectField and I am trying to display in Review the selected fields, but I have no results.

## Screenshots
Chatbot:
![image](https://user-images.githubusercontent.com/18479039/38981729-c53b31d2-43c8-11e8-8aea-8ad375d8f9d8.png)
![image](https://user-images.githubusercontent.com/18479039/38982163-cc5b6008-43c9-11e8-9380-c6e50141ff46.png)
Review:
![image](https://user-images.githubusercontent.com/18479039/38981811-f1a1ab8e-43c8-11e8-8206-290634199ec6.png)
MultiSelectField:
![image](https://user-images.githubusercontent.com/18479039/38981884-1cfe73e8-43c9-11e8-9a03-c1b530ce207f.png)

**Comment by LucasBassetti** [comment]
HI @DianaCristina,

I recommend you use the `steps` prop to pass variables between custom components. Check the properties [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component)
