### ISSUE TITLE
Can Bot Speak message and it have that feature?

### ISSUE THREAD

**Issue by kbmanikanta** [LucasBassetti/react-simple-chatbot#88]
## Description

Hi can anyone please let me know, can this module have bot speak messages feature.

## Screenshots

Add screenshots case needes, otherwise delete this section.

**Comment by LucasBassetti** [comment]
Hi @kbmanikanta,

There is a Speech Recognition just for users. Check [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/speech-recognition)
