### ISSUE TITLE
Make the chat Fullscreen

### ISSUE THREAD

**Issue by marcosbarbosa031** [LucasBassetti/react-simple-chatbot#89]
Hi @LucasBassetti,  congratulations with theproject.
I would like to know if there's a way to make the chat fill all the browser window?
I know that we can put the width at the maximum to fill horizontally, but there's no height property to fill the windowo vertically. It's there a way to accomplish this?

Thanks in advance.

**Comment by alexdalecki** [comment]
Try something like this:

`<ChatBot
        contentStyle={{
          height: 'auto',
          'minHeight' : '400px',
          'overflowY' : 'auto'
        }}
/>`

**Comment by alexdalecki** [comment]
`<ChatBot style={{ height: 'auto', 'minHeight' : '400px', 'overflowY' : 'auto' }} />` could work as well.

**Comment by LucasBassetti** [comment]
Hi, you can use the `<ChatBot style={{ height: '100vh' }} />`

**Comment by icegeek22** [comment]
How to put the width at maximum to fill horizontally?
