### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by dmr** [LucasBassetti/react-simple-chatbot#9]
Hi, I really like your simple chatbot code, thank you!

To apply it in my projects I'd have to change the style quite a bit and I was wondering if you would accept a pullrequest that implemented "Theming" as described in styled-components:
https://www.styled-components.com/docs/advanced#theming

This is just a first thought but how do you feel about the idea?

**Comment by LucasBassetti** [comment]
Hi, Thanks! :)

It seems a great idea! Will the theme impact just in colors?

**Comment by dmr** [comment]
I hope that I can overwride paddings and colors and fonts with it. Still have to find the time to build it...

**Comment by dmr** [comment]
I attached some code in #10.
