### ISSUE TITLE
Hello, i install npm process but i don't know, how create dummy running proyect

### ISSUE THREAD

**Issue by redesitos** [LucasBassetti/react-simple-chatbot#91]
Greetings.

hello made the installation with the procedure that you comment on git but I do not know what happens next if you must do a fictitious test, I am new to this and I would like to know what files I should create under what names and how I could execute it.

Thank you very much.

**Comment by LucasBassetti** [comment]
Hi @redesitos,

Take a look in the [Website](https://lucasbassetti.com.br/react-simple-chatbot/). You will find some example there.
