### ISSUE TITLE
memory leak with axios get request

### ISSUE THREAD

**Issue by MartynasDru** [LucasBassetti/react-simple-chatbot#92]
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

This error is thrown if i try to unmount chatbot while anyone is typing.

As i guess this error happens because of set timeouts and intervals inside chatbot? 
Maybe some thoughts how i could clear them before unmounting chatbot or other solutions?

**Comment by LucasBassetti** [comment]
Hi @MartynasDru,

Can you share your code?
