### ISSUE TITLE
Getting warnings while install

### ISSUE THREAD

**Issue by icegeek22** [LucasBassetti/react-simple-chatbot#94]
Hi, I was trying to install using `npm i react-simple-chatbot --save` and got these following warnings. How to remove these warnings?
![react](https://user-images.githubusercontent.com/36874634/39747595-5a879d50-52cb-11e8-8394-b1ec9680ae26.png)

**Comment by jazzkonnen** [comment]
`npm init`
will solve the issue with not having a json, no description etc...
For the three dependencies, you must save the release
`npm install react@16.x.x --save-dev`

**Comment by icegeek22** [comment]
Thanks.
