### ISSUE TITLE
Take input through speech

### ISSUE THREAD

**Issue by icegeek22** [LucasBassetti/react-simple-chatbot#95]
How to take input from user through speech instead of text? Can we use Google's Speech API for the same, if so, how?

**Comment by LucasBassetti** [comment]
Hi @icegeek22,

You can do that just adding the `recognitionEnable` prop in the Chatbot.

Like that: `<Chatbot recognitionEnable={true} />`

You can see an example [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/speech-recognition)

**Comment by icegeek22** [comment]
Thanks for that Lucas. Please tell whether there is a daily limit to speech inputs or I can take as many speech inputs as I like.
