### ISSUE TITLE
Speech API

### ISSUE THREAD

**Issue by icegeek22** [LucasBassetti/react-simple-chatbot#97]
Hi, Lucas can you please tell which API you have used for speech to text conversion? Is it Google's web speech API or some other open-source API?

**Comment by LucasBassetti** [comment]
HTML5 Speech Recognition

**Comment by icegeek22** [comment]
Lucas can you please point out in the code where you have integrated this API.

**Comment by scq000** [comment]
Hi, I want to use another speech api, can we customize it?

**Comment by scq000** [comment]
@LucasBassetti

**Comment by predictron-cloud** [comment]
+1
