### ISSUE TITLE
Able to press 'enter' multiple times on input field on Safari

### ISSUE THREAD

**Issue by aaronkrohn** [LucasBassetti/react-simple-chatbot#98]
## Description

User is able to press `enter` on the keyboard multiple times when asked to enter information in the input field. This is only a bug on Safari.

## Screenshots

<img width="401" alt="screen shot 2018-05-24 at 14 46 25" src="https://user-images.githubusercontent.com/15049081/40489611-63367348-5f61-11e8-9eb8-09c3fd13e879.png">

**Comment by LucasBassetti** [comment]
Fixed on `0.3.0`. Thanks!

**Comment by aaronkrohn** [comment]
@LucasBassetti Perfect thanks. Great project!
