### ISSUE TITLE
Speech Recognization mike not working in firefox browser

### ISSUE THREAD

**Issue by Srinu-lenka** [LucasBassetti/react-simple-chatbot#99]
Hi Lucas,

Your chatbot application is awasome speech recognization working in chrome but not working in other browsers like firefox,IE please give me some suggestion to work out.
![mike](https://user-images.githubusercontent.com/39688030/40637872-75691792-6325-11e8-985e-ec4c67a59706.png)

**Comment by icegeek22** [comment]
I think it only works on Google Chrome.

**Comment by LucasBassetti** [comment]
Unfortunately it only works on Google Chrome.
[https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Browser_compatibility)
